// @generated by protoc-gen-es v1.10.1 with parameter "target=ts+dts"
// @generated from file player/v1/player.proto (package player.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Request to get a player by ID
 *
 * @generated from message player.v1.GetPlayerRequest
 */
export class GetPlayerRequest extends Message<GetPlayerRequest> {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId = "";

  constructor(data?: PartialMessage<GetPlayerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.GetPlayerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPlayerRequest {
    return new GetPlayerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPlayerRequest {
    return new GetPlayerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPlayerRequest {
    return new GetPlayerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPlayerRequest | PlainMessage<GetPlayerRequest> | undefined, b: GetPlayerRequest | PlainMessage<GetPlayerRequest> | undefined): boolean {
    return proto3.util.equals(GetPlayerRequest, a, b);
  }
}

/**
 * Response containing a player
 *
 * @generated from message player.v1.GetPlayerResponse
 */
export class GetPlayerResponse extends Message<GetPlayerResponse> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<GetPlayerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.GetPlayerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player", kind: "message", T: Player },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPlayerResponse {
    return new GetPlayerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPlayerResponse {
    return new GetPlayerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPlayerResponse {
    return new GetPlayerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetPlayerResponse | PlainMessage<GetPlayerResponse> | undefined, b: GetPlayerResponse | PlainMessage<GetPlayerResponse> | undefined): boolean {
    return proto3.util.equals(GetPlayerResponse, a, b);
  }
}

/**
 * Request to get all players
 *
 * @generated from message player.v1.GetAllPlayersRequest
 */
export class GetAllPlayersRequest extends Message<GetAllPlayersRequest> {
  constructor(data?: PartialMessage<GetAllPlayersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.GetAllPlayersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllPlayersRequest {
    return new GetAllPlayersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllPlayersRequest {
    return new GetAllPlayersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllPlayersRequest {
    return new GetAllPlayersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAllPlayersRequest | PlainMessage<GetAllPlayersRequest> | undefined, b: GetAllPlayersRequest | PlainMessage<GetAllPlayersRequest> | undefined): boolean {
    return proto3.util.equals(GetAllPlayersRequest, a, b);
  }
}

/**
 * Response containing all players
 *
 * @generated from message player.v1.GetAllPlayersResponse
 */
export class GetAllPlayersResponse extends Message<GetAllPlayersResponse> {
  /**
   * @generated from field: repeated player.v1.Player player = 1;
   */
  player: Player[] = [];

  constructor(data?: PartialMessage<GetAllPlayersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.GetAllPlayersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player", kind: "message", T: Player, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllPlayersResponse {
    return new GetAllPlayersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllPlayersResponse {
    return new GetAllPlayersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllPlayersResponse {
    return new GetAllPlayersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAllPlayersResponse | PlainMessage<GetAllPlayersResponse> | undefined, b: GetAllPlayersResponse | PlainMessage<GetAllPlayersResponse> | undefined): boolean {
    return proto3.util.equals(GetAllPlayersResponse, a, b);
  }
}

/**
 * Request to create a player
 *
 * @generated from message player.v1.CreatePlayerRequest
 */
export class CreatePlayerRequest extends Message<CreatePlayerRequest> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<CreatePlayerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.CreatePlayerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player", kind: "message", T: Player },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlayerRequest {
    return new CreatePlayerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlayerRequest {
    return new CreatePlayerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlayerRequest {
    return new CreatePlayerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlayerRequest | PlainMessage<CreatePlayerRequest> | undefined, b: CreatePlayerRequest | PlainMessage<CreatePlayerRequest> | undefined): boolean {
    return proto3.util.equals(CreatePlayerRequest, a, b);
  }
}

/**
 * Response containing the created player
 *
 * @generated from message player.v1.CreatePlayerResponse
 */
export class CreatePlayerResponse extends Message<CreatePlayerResponse> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<CreatePlayerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.CreatePlayerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player", kind: "message", T: Player },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlayerResponse {
    return new CreatePlayerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlayerResponse {
    return new CreatePlayerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlayerResponse {
    return new CreatePlayerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlayerResponse | PlainMessage<CreatePlayerResponse> | undefined, b: CreatePlayerResponse | PlainMessage<CreatePlayerResponse> | undefined): boolean {
    return proto3.util.equals(CreatePlayerResponse, a, b);
  }
}

/**
 * Request to update a player
 *
 * @generated from message player.v1.UpdatePlayerRequest
 */
export class UpdatePlayerRequest extends Message<UpdatePlayerRequest> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<UpdatePlayerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.UpdatePlayerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player", kind: "message", T: Player },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdatePlayerRequest {
    return new UpdatePlayerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdatePlayerRequest {
    return new UpdatePlayerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdatePlayerRequest {
    return new UpdatePlayerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdatePlayerRequest | PlainMessage<UpdatePlayerRequest> | undefined, b: UpdatePlayerRequest | PlainMessage<UpdatePlayerRequest> | undefined): boolean {
    return proto3.util.equals(UpdatePlayerRequest, a, b);
  }
}

/**
 * Response containing the updated player
 *
 * @generated from message player.v1.UpdatePlayerResponse
 */
export class UpdatePlayerResponse extends Message<UpdatePlayerResponse> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<UpdatePlayerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.UpdatePlayerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player", kind: "message", T: Player },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdatePlayerResponse {
    return new UpdatePlayerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdatePlayerResponse {
    return new UpdatePlayerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdatePlayerResponse {
    return new UpdatePlayerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdatePlayerResponse | PlainMessage<UpdatePlayerResponse> | undefined, b: UpdatePlayerResponse | PlainMessage<UpdatePlayerResponse> | undefined): boolean {
    return proto3.util.equals(UpdatePlayerResponse, a, b);
  }
}

/**
 * Player message
 *
 * @generated from message player.v1.Player
 */
export class Player extends Message<Player> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string emoji = 2;
   */
  emoji = "";

  /**
   * @generated from field: repeated int32 emoji_codepoints = 3;
   */
  emojiCodepoints: number[] = [];

  /**
   * @generated from field: repeated string beji_ids = 4;
   */
  bejiIds: string[] = [];

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt = protoInt64.zero;

  constructor(data?: PartialMessage<Player>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "player.v1.Player";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "emoji_codepoints", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 4, name: "beji_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "created_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player {
    return new Player().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player {
    return new Player().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player {
    return new Player().fromJsonString(jsonString, options);
  }

  static equals(a: Player | PlainMessage<Player> | undefined, b: Player | PlainMessage<Player> | undefined): boolean {
    return proto3.util.equals(Player, a, b);
  }
}

