// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file player/v1/player.proto (package player.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Beji } from "../../beji/v1/beji_pb";

/**
 * Describes the file player/v1/player.proto.
 */
export declare const file_player_v1_player: GenFile;

/**
 * Request to get a player by ID
 *
 * @generated from message player.v1.GetPlayerRequest
 */
export declare type GetPlayerRequest = Message<"player.v1.GetPlayerRequest"> & {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;
};

/**
 * Describes the message player.v1.GetPlayerRequest.
 * Use `create(GetPlayerRequestSchema)` to create a new message.
 */
export declare const GetPlayerRequestSchema: GenMessage<GetPlayerRequest>;

/**
 * Response containing a player
 *
 * @generated from message player.v1.GetPlayerResponse
 */
export declare type GetPlayerResponse = Message<"player.v1.GetPlayerResponse"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.GetPlayerResponse.
 * Use `create(GetPlayerResponseSchema)` to create a new message.
 */
export declare const GetPlayerResponseSchema: GenMessage<GetPlayerResponse>;

/**
 * Request to get all players
 *
 * @generated from message player.v1.GetAllPlayersRequest
 */
export declare type GetAllPlayersRequest = Message<"player.v1.GetAllPlayersRequest"> & {
};

/**
 * Describes the message player.v1.GetAllPlayersRequest.
 * Use `create(GetAllPlayersRequestSchema)` to create a new message.
 */
export declare const GetAllPlayersRequestSchema: GenMessage<GetAllPlayersRequest>;

/**
 * Response containing all players
 *
 * @generated from message player.v1.GetAllPlayersResponse
 */
export declare type GetAllPlayersResponse = Message<"player.v1.GetAllPlayersResponse"> & {
  /**
   * @generated from field: repeated player.v1.Player player = 1;
   */
  player: Player[];
};

/**
 * Describes the message player.v1.GetAllPlayersResponse.
 * Use `create(GetAllPlayersResponseSchema)` to create a new message.
 */
export declare const GetAllPlayersResponseSchema: GenMessage<GetAllPlayersResponse>;

/**
 * Request to create a player
 *
 * @generated from message player.v1.CreatePlayerRequest
 */
export declare type CreatePlayerRequest = Message<"player.v1.CreatePlayerRequest"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.CreatePlayerRequest.
 * Use `create(CreatePlayerRequestSchema)` to create a new message.
 */
export declare const CreatePlayerRequestSchema: GenMessage<CreatePlayerRequest>;

/**
 * Response containing the created player
 *
 * @generated from message player.v1.CreatePlayerResponse
 */
export declare type CreatePlayerResponse = Message<"player.v1.CreatePlayerResponse"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.CreatePlayerResponse.
 * Use `create(CreatePlayerResponseSchema)` to create a new message.
 */
export declare const CreatePlayerResponseSchema: GenMessage<CreatePlayerResponse>;

/**
 * Request to update a player
 *
 * @generated from message player.v1.UpdatePlayerRequest
 */
export declare type UpdatePlayerRequest = Message<"player.v1.UpdatePlayerRequest"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.UpdatePlayerRequest.
 * Use `create(UpdatePlayerRequestSchema)` to create a new message.
 */
export declare const UpdatePlayerRequestSchema: GenMessage<UpdatePlayerRequest>;

/**
 * Response containing the updated player
 *
 * @generated from message player.v1.UpdatePlayerResponse
 */
export declare type UpdatePlayerResponse = Message<"player.v1.UpdatePlayerResponse"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.UpdatePlayerResponse.
 * Use `create(UpdatePlayerResponseSchema)` to create a new message.
 */
export declare const UpdatePlayerResponseSchema: GenMessage<UpdatePlayerResponse>;

/**
 * Player message
 *
 * @generated from message player.v1.Player
 */
export declare type Player = Message<"player.v1.Player"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string emoji = 2;
   */
  emoji: string;

  /**
   * @generated from field: repeated int32 emoji_codepoints = 3;
   */
  emojiCodepoints: number[];

  /**
   * @generated from field: repeated string beji_ids = 4;
   */
  bejiIds: string[];

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt: bigint;
};

/**
 * Describes the message player.v1.Player.
 * Use `create(PlayerSchema)` to create a new message.
 */
export declare const PlayerSchema: GenMessage<Player>;

/**
 * Request to get all bejis for a user
 *
 * @generated from message player.v1.GetUserBejisRequest
 */
export declare type GetUserBejisRequest = Message<"player.v1.GetUserBejisRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message player.v1.GetUserBejisRequest.
 * Use `create(GetUserBejisRequestSchema)` to create a new message.
 */
export declare const GetUserBejisRequestSchema: GenMessage<GetUserBejisRequest>;

/**
 * Response containing bejis with their world information
 *
 * @generated from message player.v1.GetUserBejisResponse
 */
export declare type GetUserBejisResponse = Message<"player.v1.GetUserBejisResponse"> & {
  /**
   * @generated from field: repeated player.v1.BejiWithWorld bejis = 1;
   */
  bejis: BejiWithWorld[];
};

/**
 * Describes the message player.v1.GetUserBejisResponse.
 * Use `create(GetUserBejisResponseSchema)` to create a new message.
 */
export declare const GetUserBejisResponseSchema: GenMessage<GetUserBejisResponse>;

/**
 * Beji with associated world summary
 *
 * @generated from message player.v1.BejiWithWorld
 */
export declare type BejiWithWorld = Message<"player.v1.BejiWithWorld"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  /**
   * @generated from field: player.v1.WorldSummary world = 2;
   */
  world?: WorldSummary;
};

/**
 * Describes the message player.v1.BejiWithWorld.
 * Use `create(BejiWithWorldSchema)` to create a new message.
 */
export declare const BejiWithWorldSchema: GenMessage<BejiWithWorld>;

/**
 * Summary of a world (subset of world data)
 *
 * @generated from message player.v1.WorldSummary
 */
export declare type WorldSummary = Message<"player.v1.WorldSummary"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string main_beji_id = 2;
   */
  mainBejiId: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;
};

/**
 * Describes the message player.v1.WorldSummary.
 * Use `create(WorldSummarySchema)` to create a new message.
 */
export declare const WorldSummarySchema: GenMessage<WorldSummary>;

/**
 * Player service for managing player entities
 *
 * @generated from service player.v1.PlayerService
 */
export declare const PlayerService: GenService<{
  /**
   * GetPlayer retrieves a player by ID
   *
   * @generated from rpc player.v1.PlayerService.GetPlayer
   */
  getPlayer: {
    methodKind: "unary";
    input: typeof GetPlayerRequestSchema;
    output: typeof GetPlayerResponseSchema;
  },
  /**
   * GetAllPlayers retrieves all players
   *
   * @generated from rpc player.v1.PlayerService.GetAllPlayers
   */
  getAllPlayers: {
    methodKind: "unary";
    input: typeof GetAllPlayersRequestSchema;
    output: typeof GetAllPlayersResponseSchema;
  },
  /**
   * CreatePlayer creates a new player
   *
   * @generated from rpc player.v1.PlayerService.CreatePlayer
   */
  createPlayer: {
    methodKind: "unary";
    input: typeof CreatePlayerRequestSchema;
    output: typeof CreatePlayerResponseSchema;
  },
  /**
   * UpdatePlayer updates an existing player
   *
   * @generated from rpc player.v1.PlayerService.UpdatePlayer
   */
  updatePlayer: {
    methodKind: "unary";
    input: typeof UpdatePlayerRequestSchema;
    output: typeof UpdatePlayerResponseSchema;
  },
}>;

