// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts+dts"
// @generated from file player/v1/player.proto (package player.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatePlayerRequest, CreatePlayerResponse, GetAllPlayersRequest, GetAllPlayersResponse, GetPlayerRequest, GetPlayerResponse, UpdatePlayerRequest, UpdatePlayerResponse } from "./player_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Player service for managing player entities
 *
 * @generated from service player.v1.PlayerService
 */
export const PlayerService = {
  typeName: "player.v1.PlayerService",
  methods: {
    /**
     * GetPlayer retrieves a player by ID
     *
     * @generated from rpc player.v1.PlayerService.GetPlayer
     */
    getPlayer: {
      name: "GetPlayer",
      I: GetPlayerRequest,
      O: GetPlayerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetAllPlayers retrieves all players
     *
     * @generated from rpc player.v1.PlayerService.GetAllPlayers
     */
    getAllPlayers: {
      name: "GetAllPlayers",
      I: GetAllPlayersRequest,
      O: GetAllPlayersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreatePlayer creates a new player
     *
     * @generated from rpc player.v1.PlayerService.CreatePlayer
     */
    createPlayer: {
      name: "CreatePlayer",
      I: CreatePlayerRequest,
      O: CreatePlayerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdatePlayer updates an existing player
     *
     * @generated from rpc player.v1.PlayerService.UpdatePlayer
     */
    updatePlayer: {
      name: "UpdatePlayer",
      I: UpdatePlayerRequest,
      O: UpdatePlayerResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

