// @generated by protoc-gen-es v1.10.1 with parameter "target=ts+dts"
// @generated from file player/v1/player.proto (package player.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Beji } from "../../beji/v1/beji_pb";

/**
 * Request to get a player by ID
 *
 * @generated from message player.v1.GetPlayerRequest
 */
export declare class GetPlayerRequest extends Message<GetPlayerRequest> {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;

  constructor(data?: PartialMessage<GetPlayerRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.GetPlayerRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPlayerRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPlayerRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPlayerRequest;

  static equals(a: GetPlayerRequest | PlainMessage<GetPlayerRequest> | undefined, b: GetPlayerRequest | PlainMessage<GetPlayerRequest> | undefined): boolean;
}

/**
 * Response containing a player
 *
 * @generated from message player.v1.GetPlayerResponse
 */
export declare class GetPlayerResponse extends Message<GetPlayerResponse> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<GetPlayerResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.GetPlayerResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPlayerResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPlayerResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPlayerResponse;

  static equals(a: GetPlayerResponse | PlainMessage<GetPlayerResponse> | undefined, b: GetPlayerResponse | PlainMessage<GetPlayerResponse> | undefined): boolean;
}

/**
 * Request to get all players
 *
 * @generated from message player.v1.GetAllPlayersRequest
 */
export declare class GetAllPlayersRequest extends Message<GetAllPlayersRequest> {
  constructor(data?: PartialMessage<GetAllPlayersRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.GetAllPlayersRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllPlayersRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllPlayersRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllPlayersRequest;

  static equals(a: GetAllPlayersRequest | PlainMessage<GetAllPlayersRequest> | undefined, b: GetAllPlayersRequest | PlainMessage<GetAllPlayersRequest> | undefined): boolean;
}

/**
 * Response containing all players
 *
 * @generated from message player.v1.GetAllPlayersResponse
 */
export declare class GetAllPlayersResponse extends Message<GetAllPlayersResponse> {
  /**
   * @generated from field: repeated player.v1.Player player = 1;
   */
  player: Player[];

  constructor(data?: PartialMessage<GetAllPlayersResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.GetAllPlayersResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllPlayersResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllPlayersResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllPlayersResponse;

  static equals(a: GetAllPlayersResponse | PlainMessage<GetAllPlayersResponse> | undefined, b: GetAllPlayersResponse | PlainMessage<GetAllPlayersResponse> | undefined): boolean;
}

/**
 * Request to create a player
 *
 * @generated from message player.v1.CreatePlayerRequest
 */
export declare class CreatePlayerRequest extends Message<CreatePlayerRequest> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<CreatePlayerRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.CreatePlayerRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlayerRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlayerRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlayerRequest;

  static equals(a: CreatePlayerRequest | PlainMessage<CreatePlayerRequest> | undefined, b: CreatePlayerRequest | PlainMessage<CreatePlayerRequest> | undefined): boolean;
}

/**
 * Response containing the created player
 *
 * @generated from message player.v1.CreatePlayerResponse
 */
export declare class CreatePlayerResponse extends Message<CreatePlayerResponse> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<CreatePlayerResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.CreatePlayerResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlayerResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlayerResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlayerResponse;

  static equals(a: CreatePlayerResponse | PlainMessage<CreatePlayerResponse> | undefined, b: CreatePlayerResponse | PlainMessage<CreatePlayerResponse> | undefined): boolean;
}

/**
 * Request to update a player
 *
 * @generated from message player.v1.UpdatePlayerRequest
 */
export declare class UpdatePlayerRequest extends Message<UpdatePlayerRequest> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<UpdatePlayerRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.UpdatePlayerRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdatePlayerRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdatePlayerRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdatePlayerRequest;

  static equals(a: UpdatePlayerRequest | PlainMessage<UpdatePlayerRequest> | undefined, b: UpdatePlayerRequest | PlainMessage<UpdatePlayerRequest> | undefined): boolean;
}

/**
 * Response containing the updated player
 *
 * @generated from message player.v1.UpdatePlayerResponse
 */
export declare class UpdatePlayerResponse extends Message<UpdatePlayerResponse> {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;

  constructor(data?: PartialMessage<UpdatePlayerResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.UpdatePlayerResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdatePlayerResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdatePlayerResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdatePlayerResponse;

  static equals(a: UpdatePlayerResponse | PlainMessage<UpdatePlayerResponse> | undefined, b: UpdatePlayerResponse | PlainMessage<UpdatePlayerResponse> | undefined): boolean;
}

/**
 * Player message
 *
 * @generated from message player.v1.Player
 */
export declare class Player extends Message<Player> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string emoji = 2;
   */
  emoji: string;

  /**
   * @generated from field: repeated int32 emoji_codepoints = 3;
   */
  emojiCodepoints: number[];

  /**
   * @generated from field: repeated string beji_ids = 4;
   */
  bejiIds: string[];

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt: bigint;

  constructor(data?: PartialMessage<Player>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.Player";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player;

  static equals(a: Player | PlainMessage<Player> | undefined, b: Player | PlainMessage<Player> | undefined): boolean;
}

/**
 * Request to get all bejis for a user
 *
 * @generated from message player.v1.GetUserBejisRequest
 */
export declare class GetUserBejisRequest extends Message<GetUserBejisRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  constructor(data?: PartialMessage<GetUserBejisRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.GetUserBejisRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserBejisRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserBejisRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserBejisRequest;

  static equals(a: GetUserBejisRequest | PlainMessage<GetUserBejisRequest> | undefined, b: GetUserBejisRequest | PlainMessage<GetUserBejisRequest> | undefined): boolean;
}

/**
 * Response containing bejis with their world information
 *
 * @generated from message player.v1.GetUserBejisResponse
 */
export declare class GetUserBejisResponse extends Message<GetUserBejisResponse> {
  /**
   * @generated from field: repeated player.v1.BejiWithWorld bejis = 1;
   */
  bejis: BejiWithWorld[];

  constructor(data?: PartialMessage<GetUserBejisResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.GetUserBejisResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserBejisResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserBejisResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserBejisResponse;

  static equals(a: GetUserBejisResponse | PlainMessage<GetUserBejisResponse> | undefined, b: GetUserBejisResponse | PlainMessage<GetUserBejisResponse> | undefined): boolean;
}

/**
 * Beji with associated world summary
 *
 * @generated from message player.v1.BejiWithWorld
 */
export declare class BejiWithWorld extends Message<BejiWithWorld> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  /**
   * @generated from field: player.v1.WorldSummary world = 2;
   */
  world?: WorldSummary;

  constructor(data?: PartialMessage<BejiWithWorld>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.BejiWithWorld";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BejiWithWorld;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BejiWithWorld;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BejiWithWorld;

  static equals(a: BejiWithWorld | PlainMessage<BejiWithWorld> | undefined, b: BejiWithWorld | PlainMessage<BejiWithWorld> | undefined): boolean;
}

/**
 * Summary of a world (subset of world data)
 *
 * @generated from message player.v1.WorldSummary
 */
export declare class WorldSummary extends Message<WorldSummary> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string main_beji_id = 2;
   */
  mainBejiId: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;

  constructor(data?: PartialMessage<WorldSummary>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "player.v1.WorldSummary";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorldSummary;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorldSummary;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorldSummary;

  static equals(a: WorldSummary | PlainMessage<WorldSummary> | undefined, b: WorldSummary | PlainMessage<WorldSummary> | undefined): boolean;
}

