// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts+dts"
// @generated from file player/v1/player.proto (package player.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatePlayerRequest, CreatePlayerResponse, GetAllPlayersRequest, GetAllPlayersResponse, GetPlayerRequest, GetPlayerResponse, GetUserBejisRequest, GetUserBejisResponse, UpdatePlayerRequest, UpdatePlayerResponse } from "./player_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Player service for managing player entities
 *
 * @generated from service player.v1.PlayerService
 */
export declare const PlayerService: {
  readonly typeName: "player.v1.PlayerService",
  readonly methods: {
    /**
     * GetPlayer retrieves a player by ID
     *
     * @generated from rpc player.v1.PlayerService.GetPlayer
     */
    readonly getPlayer: {
      readonly name: "GetPlayer",
      readonly I: typeof GetPlayerRequest,
      readonly O: typeof GetPlayerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetAllPlayers retrieves all players
     *
     * @generated from rpc player.v1.PlayerService.GetAllPlayers
     */
    readonly getAllPlayers: {
      readonly name: "GetAllPlayers",
      readonly I: typeof GetAllPlayersRequest,
      readonly O: typeof GetAllPlayersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * CreatePlayer creates a new player
     *
     * @generated from rpc player.v1.PlayerService.CreatePlayer
     */
    readonly createPlayer: {
      readonly name: "CreatePlayer",
      readonly I: typeof CreatePlayerRequest,
      readonly O: typeof CreatePlayerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * UpdatePlayer updates an existing player
     *
     * @generated from rpc player.v1.PlayerService.UpdatePlayer
     */
    readonly updatePlayer: {
      readonly name: "UpdatePlayer",
      readonly I: typeof UpdatePlayerRequest,
      readonly O: typeof UpdatePlayerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetUserBejis retrieves all bejis for a user with their world information
     *
     * @generated from rpc player.v1.PlayerService.GetUserBejis
     */
    readonly getUserBejis: {
      readonly name: "GetUserBejis",
      readonly I: typeof GetUserBejisRequest,
      readonly O: typeof GetUserBejisResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

