// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file player/v1/player.proto (package player.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Beji } from "../../beji/v1/beji_pb";
import { file_beji_v1_beji } from "../../beji/v1/beji_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file player/v1/player.proto.
 */
export const file_player_v1_player: GenFile = /*@__PURE__*/
  fileDesc("ChZwbGF5ZXIvdjEvcGxheWVyLnByb3RvEglwbGF5ZXIudjEiJQoQR2V0UGxheWVyUmVxdWVzdBIRCglwbGF5ZXJfaWQYASABKAkiNgoRR2V0UGxheWVyUmVzcG9uc2USIQoGcGxheWVyGAEgASgLMhEucGxheWVyLnYxLlBsYXllciIWChRHZXRBbGxQbGF5ZXJzUmVxdWVzdCI6ChVHZXRBbGxQbGF5ZXJzUmVzcG9uc2USIQoGcGxheWVyGAEgAygLMhEucGxheWVyLnYxLlBsYXllciI4ChNDcmVhdGVQbGF5ZXJSZXF1ZXN0EiEKBnBsYXllchgBIAEoCzIRLnBsYXllci52MS5QbGF5ZXIiOQoUQ3JlYXRlUGxheWVyUmVzcG9uc2USIQoGcGxheWVyGAEgASgLMhEucGxheWVyLnYxLlBsYXllciI4ChNVcGRhdGVQbGF5ZXJSZXF1ZXN0EiEKBnBsYXllchgBIAEoCzIRLnBsYXllci52MS5QbGF5ZXIiOQoUVXBkYXRlUGxheWVyUmVzcG9uc2USIQoGcGxheWVyGAEgASgLMhEucGxheWVyLnYxLlBsYXllciJjCgZQbGF5ZXISCgoCaWQYASABKAkSDQoFZW1vamkYAiABKAkSGAoQZW1vamlfY29kZXBvaW50cxgDIAMoBRIQCghiZWppX2lkcxgEIAMoCRISCgpjcmVhdGVkX2F0GAUgASgDIiYKE0dldFVzZXJCZWppc1JlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCSI/ChRHZXRVc2VyQmVqaXNSZXNwb25zZRInCgViZWppcxgBIAMoCzIYLnBsYXllci52MS5CZWppV2l0aFdvcmxkIlQKDUJlamlXaXRoV29ybGQSGwoEYmVqaRgBIAEoCzINLmJlamkudjEuQmVqaRImCgV3b3JsZBgCIAEoCzIXLnBsYXllci52MS5Xb3JsZFN1bW1hcnkiRAoMV29ybGRTdW1tYXJ5EgoKAmlkGAEgASgJEhQKDG1haW5fYmVqaV9pZBgCIAEoCRISCgpjcmVhdGVkX2F0GAMgASgDMp4DCg1QbGF5ZXJTZXJ2aWNlEkYKCUdldFBsYXllchIbLnBsYXllci52MS5HZXRQbGF5ZXJSZXF1ZXN0GhwucGxheWVyLnYxLkdldFBsYXllclJlc3BvbnNlElIKDUdldEFsbFBsYXllcnMSHy5wbGF5ZXIudjEuR2V0QWxsUGxheWVyc1JlcXVlc3QaIC5wbGF5ZXIudjEuR2V0QWxsUGxheWVyc1Jlc3BvbnNlEk8KDENyZWF0ZVBsYXllchIeLnBsYXllci52MS5DcmVhdGVQbGF5ZXJSZXF1ZXN0Gh8ucGxheWVyLnYxLkNyZWF0ZVBsYXllclJlc3BvbnNlEk8KDFVwZGF0ZVBsYXllchIeLnBsYXllci52MS5VcGRhdGVQbGF5ZXJSZXF1ZXN0Gh8ucGxheWVyLnYxLlVwZGF0ZVBsYXllclJlc3BvbnNlEk8KDEdldFVzZXJCZWppcxIeLnBsYXllci52MS5HZXRVc2VyQmVqaXNSZXF1ZXN0Gh8ucGxheWVyLnYxLkdldFVzZXJCZWppc1Jlc3BvbnNlQiVaI2dpdGh1Yi5jb20vcG91eWFqb29uL2JlamkvcGxheWVyL3YxYgZwcm90bzM", [file_beji_v1_beji]);

/**
 * Request to get a player by ID
 *
 * @generated from message player.v1.GetPlayerRequest
 */
export type GetPlayerRequest = Message<"player.v1.GetPlayerRequest"> & {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;
};

/**
 * Describes the message player.v1.GetPlayerRequest.
 * Use `create(GetPlayerRequestSchema)` to create a new message.
 */
export const GetPlayerRequestSchema: GenMessage<GetPlayerRequest> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 0);

/**
 * Response containing a player
 *
 * @generated from message player.v1.GetPlayerResponse
 */
export type GetPlayerResponse = Message<"player.v1.GetPlayerResponse"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.GetPlayerResponse.
 * Use `create(GetPlayerResponseSchema)` to create a new message.
 */
export const GetPlayerResponseSchema: GenMessage<GetPlayerResponse> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 1);

/**
 * Request to get all players
 *
 * @generated from message player.v1.GetAllPlayersRequest
 */
export type GetAllPlayersRequest = Message<"player.v1.GetAllPlayersRequest"> & {
};

/**
 * Describes the message player.v1.GetAllPlayersRequest.
 * Use `create(GetAllPlayersRequestSchema)` to create a new message.
 */
export const GetAllPlayersRequestSchema: GenMessage<GetAllPlayersRequest> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 2);

/**
 * Response containing all players
 *
 * @generated from message player.v1.GetAllPlayersResponse
 */
export type GetAllPlayersResponse = Message<"player.v1.GetAllPlayersResponse"> & {
  /**
   * @generated from field: repeated player.v1.Player player = 1;
   */
  player: Player[];
};

/**
 * Describes the message player.v1.GetAllPlayersResponse.
 * Use `create(GetAllPlayersResponseSchema)` to create a new message.
 */
export const GetAllPlayersResponseSchema: GenMessage<GetAllPlayersResponse> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 3);

/**
 * Request to create a player
 *
 * @generated from message player.v1.CreatePlayerRequest
 */
export type CreatePlayerRequest = Message<"player.v1.CreatePlayerRequest"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.CreatePlayerRequest.
 * Use `create(CreatePlayerRequestSchema)` to create a new message.
 */
export const CreatePlayerRequestSchema: GenMessage<CreatePlayerRequest> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 4);

/**
 * Response containing the created player
 *
 * @generated from message player.v1.CreatePlayerResponse
 */
export type CreatePlayerResponse = Message<"player.v1.CreatePlayerResponse"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.CreatePlayerResponse.
 * Use `create(CreatePlayerResponseSchema)` to create a new message.
 */
export const CreatePlayerResponseSchema: GenMessage<CreatePlayerResponse> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 5);

/**
 * Request to update a player
 *
 * @generated from message player.v1.UpdatePlayerRequest
 */
export type UpdatePlayerRequest = Message<"player.v1.UpdatePlayerRequest"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.UpdatePlayerRequest.
 * Use `create(UpdatePlayerRequestSchema)` to create a new message.
 */
export const UpdatePlayerRequestSchema: GenMessage<UpdatePlayerRequest> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 6);

/**
 * Response containing the updated player
 *
 * @generated from message player.v1.UpdatePlayerResponse
 */
export type UpdatePlayerResponse = Message<"player.v1.UpdatePlayerResponse"> & {
  /**
   * @generated from field: player.v1.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message player.v1.UpdatePlayerResponse.
 * Use `create(UpdatePlayerResponseSchema)` to create a new message.
 */
export const UpdatePlayerResponseSchema: GenMessage<UpdatePlayerResponse> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 7);

/**
 * Player message
 *
 * @generated from message player.v1.Player
 */
export type Player = Message<"player.v1.Player"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string emoji = 2;
   */
  emoji: string;

  /**
   * @generated from field: repeated int32 emoji_codepoints = 3;
   */
  emojiCodepoints: number[];

  /**
   * @generated from field: repeated string beji_ids = 4;
   */
  bejiIds: string[];

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt: bigint;
};

/**
 * Describes the message player.v1.Player.
 * Use `create(PlayerSchema)` to create a new message.
 */
export const PlayerSchema: GenMessage<Player> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 8);

/**
 * Request to get all bejis for a user
 *
 * @generated from message player.v1.GetUserBejisRequest
 */
export type GetUserBejisRequest = Message<"player.v1.GetUserBejisRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message player.v1.GetUserBejisRequest.
 * Use `create(GetUserBejisRequestSchema)` to create a new message.
 */
export const GetUserBejisRequestSchema: GenMessage<GetUserBejisRequest> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 9);

/**
 * Response containing bejis with their world information
 *
 * @generated from message player.v1.GetUserBejisResponse
 */
export type GetUserBejisResponse = Message<"player.v1.GetUserBejisResponse"> & {
  /**
   * @generated from field: repeated player.v1.BejiWithWorld bejis = 1;
   */
  bejis: BejiWithWorld[];
};

/**
 * Describes the message player.v1.GetUserBejisResponse.
 * Use `create(GetUserBejisResponseSchema)` to create a new message.
 */
export const GetUserBejisResponseSchema: GenMessage<GetUserBejisResponse> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 10);

/**
 * Beji with associated world summary
 *
 * @generated from message player.v1.BejiWithWorld
 */
export type BejiWithWorld = Message<"player.v1.BejiWithWorld"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  /**
   * @generated from field: player.v1.WorldSummary world = 2;
   */
  world?: WorldSummary;
};

/**
 * Describes the message player.v1.BejiWithWorld.
 * Use `create(BejiWithWorldSchema)` to create a new message.
 */
export const BejiWithWorldSchema: GenMessage<BejiWithWorld> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 11);

/**
 * Summary of a world (subset of world data)
 *
 * @generated from message player.v1.WorldSummary
 */
export type WorldSummary = Message<"player.v1.WorldSummary"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string main_beji_id = 2;
   */
  mainBejiId: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;
};

/**
 * Describes the message player.v1.WorldSummary.
 * Use `create(WorldSummarySchema)` to create a new message.
 */
export const WorldSummarySchema: GenMessage<WorldSummary> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 12);

/**
 * Player service for managing player entities
 *
 * @generated from service player.v1.PlayerService
 */
export const PlayerService: GenService<{
  /**
   * GetPlayer retrieves a player by ID
   *
   * @generated from rpc player.v1.PlayerService.GetPlayer
   */
  getPlayer: {
    methodKind: "unary";
    input: typeof GetPlayerRequestSchema;
    output: typeof GetPlayerResponseSchema;
  },
  /**
   * GetAllPlayers retrieves all players
   *
   * @generated from rpc player.v1.PlayerService.GetAllPlayers
   */
  getAllPlayers: {
    methodKind: "unary";
    input: typeof GetAllPlayersRequestSchema;
    output: typeof GetAllPlayersResponseSchema;
  },
  /**
   * CreatePlayer creates a new player
   *
   * @generated from rpc player.v1.PlayerService.CreatePlayer
   */
  createPlayer: {
    methodKind: "unary";
    input: typeof CreatePlayerRequestSchema;
    output: typeof CreatePlayerResponseSchema;
  },
  /**
   * UpdatePlayer updates an existing player
   *
   * @generated from rpc player.v1.PlayerService.UpdatePlayer
   */
  updatePlayer: {
    methodKind: "unary";
    input: typeof UpdatePlayerRequestSchema;
    output: typeof UpdatePlayerResponseSchema;
  },
  /**
   * GetUserBejis retrieves all bejis for a user with their world information
   *
   * @generated from rpc player.v1.PlayerService.GetUserBejis
   */
  getUserBejis: {
    methodKind: "unary";
    input: typeof GetUserBejisRequestSchema;
    output: typeof GetUserBejisResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_player_v1_player, 0);

