// @generated by protoc-gen-es v1.10.1 with parameter "target=ts+dts"
// @generated from file beji/v1/beji.proto (package beji.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Position } from "../../common/v1/common_pb";

/**
 * Request to get a beji by ID
 *
 * @generated from message beji.v1.GetBejiRequest
 */
export class GetBejiRequest extends Message<GetBejiRequest> {
  /**
   * @generated from field: string beji_id = 1;
   */
  bejiId = "";

  constructor(data?: PartialMessage<GetBejiRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.GetBejiRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBejiRequest {
    return new GetBejiRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBejiRequest {
    return new GetBejiRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBejiRequest {
    return new GetBejiRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetBejiRequest | PlainMessage<GetBejiRequest> | undefined, b: GetBejiRequest | PlainMessage<GetBejiRequest> | undefined): boolean {
    return proto3.util.equals(GetBejiRequest, a, b);
  }
}

/**
 * Response containing a beji
 *
 * @generated from message beji.v1.GetBejiResponse
 */
export class GetBejiResponse extends Message<GetBejiResponse> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<GetBejiResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.GetBejiResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji", kind: "message", T: Beji },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBejiResponse {
    return new GetBejiResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBejiResponse {
    return new GetBejiResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBejiResponse {
    return new GetBejiResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetBejiResponse | PlainMessage<GetBejiResponse> | undefined, b: GetBejiResponse | PlainMessage<GetBejiResponse> | undefined): boolean {
    return proto3.util.equals(GetBejiResponse, a, b);
  }
}

/**
 * Request to get beji for a player
 *
 * @generated from message beji.v1.GetBejiForPlayerRequest
 */
export class GetBejiForPlayerRequest extends Message<GetBejiForPlayerRequest> {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId = "";

  constructor(data?: PartialMessage<GetBejiForPlayerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.GetBejiForPlayerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBejiForPlayerRequest {
    return new GetBejiForPlayerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBejiForPlayerRequest {
    return new GetBejiForPlayerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBejiForPlayerRequest {
    return new GetBejiForPlayerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetBejiForPlayerRequest | PlainMessage<GetBejiForPlayerRequest> | undefined, b: GetBejiForPlayerRequest | PlainMessage<GetBejiForPlayerRequest> | undefined): boolean {
    return proto3.util.equals(GetBejiForPlayerRequest, a, b);
  }
}

/**
 * Response containing beji for a player
 *
 * @generated from message beji.v1.GetBejiForPlayerResponse
 */
export class GetBejiForPlayerResponse extends Message<GetBejiForPlayerResponse> {
  /**
   * @generated from field: repeated beji.v1.Beji beji = 1;
   */
  beji: Beji[] = [];

  constructor(data?: PartialMessage<GetBejiForPlayerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.GetBejiForPlayerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji", kind: "message", T: Beji, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBejiForPlayerResponse {
    return new GetBejiForPlayerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBejiForPlayerResponse {
    return new GetBejiForPlayerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBejiForPlayerResponse {
    return new GetBejiForPlayerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetBejiForPlayerResponse | PlainMessage<GetBejiForPlayerResponse> | undefined, b: GetBejiForPlayerResponse | PlainMessage<GetBejiForPlayerResponse> | undefined): boolean {
    return proto3.util.equals(GetBejiForPlayerResponse, a, b);
  }
}

/**
 * Request to get all beji
 *
 * @generated from message beji.v1.GetAllBejiRequest
 */
export class GetAllBejiRequest extends Message<GetAllBejiRequest> {
  constructor(data?: PartialMessage<GetAllBejiRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.GetAllBejiRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllBejiRequest {
    return new GetAllBejiRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllBejiRequest {
    return new GetAllBejiRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllBejiRequest {
    return new GetAllBejiRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAllBejiRequest | PlainMessage<GetAllBejiRequest> | undefined, b: GetAllBejiRequest | PlainMessage<GetAllBejiRequest> | undefined): boolean {
    return proto3.util.equals(GetAllBejiRequest, a, b);
  }
}

/**
 * Response containing all beji
 *
 * @generated from message beji.v1.GetAllBejiResponse
 */
export class GetAllBejiResponse extends Message<GetAllBejiResponse> {
  /**
   * @generated from field: repeated beji.v1.Beji beji = 1;
   */
  beji: Beji[] = [];

  constructor(data?: PartialMessage<GetAllBejiResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.GetAllBejiResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji", kind: "message", T: Beji, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllBejiResponse {
    return new GetAllBejiResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllBejiResponse {
    return new GetAllBejiResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllBejiResponse {
    return new GetAllBejiResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAllBejiResponse | PlainMessage<GetAllBejiResponse> | undefined, b: GetAllBejiResponse | PlainMessage<GetAllBejiResponse> | undefined): boolean {
    return proto3.util.equals(GetAllBejiResponse, a, b);
  }
}

/**
 * Request to create a beji
 *
 * @generated from message beji.v1.CreateBejiRequest
 */
export class CreateBejiRequest extends Message<CreateBejiRequest> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<CreateBejiRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.CreateBejiRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji", kind: "message", T: Beji },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBejiRequest {
    return new CreateBejiRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBejiRequest {
    return new CreateBejiRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBejiRequest {
    return new CreateBejiRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateBejiRequest | PlainMessage<CreateBejiRequest> | undefined, b: CreateBejiRequest | PlainMessage<CreateBejiRequest> | undefined): boolean {
    return proto3.util.equals(CreateBejiRequest, a, b);
  }
}

/**
 * Response containing the created beji
 *
 * @generated from message beji.v1.CreateBejiResponse
 */
export class CreateBejiResponse extends Message<CreateBejiResponse> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<CreateBejiResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.CreateBejiResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji", kind: "message", T: Beji },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBejiResponse {
    return new CreateBejiResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBejiResponse {
    return new CreateBejiResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBejiResponse {
    return new CreateBejiResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateBejiResponse | PlainMessage<CreateBejiResponse> | undefined, b: CreateBejiResponse | PlainMessage<CreateBejiResponse> | undefined): boolean {
    return proto3.util.equals(CreateBejiResponse, a, b);
  }
}

/**
 * Request to update a beji
 *
 * @generated from message beji.v1.UpdateBejiRequest
 */
export class UpdateBejiRequest extends Message<UpdateBejiRequest> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<UpdateBejiRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.UpdateBejiRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji", kind: "message", T: Beji },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateBejiRequest {
    return new UpdateBejiRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateBejiRequest {
    return new UpdateBejiRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateBejiRequest {
    return new UpdateBejiRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateBejiRequest | PlainMessage<UpdateBejiRequest> | undefined, b: UpdateBejiRequest | PlainMessage<UpdateBejiRequest> | undefined): boolean {
    return proto3.util.equals(UpdateBejiRequest, a, b);
  }
}

/**
 * Response containing the updated beji
 *
 * @generated from message beji.v1.UpdateBejiResponse
 */
export class UpdateBejiResponse extends Message<UpdateBejiResponse> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<UpdateBejiResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.UpdateBejiResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji", kind: "message", T: Beji },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateBejiResponse {
    return new UpdateBejiResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateBejiResponse {
    return new UpdateBejiResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateBejiResponse {
    return new UpdateBejiResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateBejiResponse | PlainMessage<UpdateBejiResponse> | undefined, b: UpdateBejiResponse | PlainMessage<UpdateBejiResponse> | undefined): boolean {
    return proto3.util.equals(UpdateBejiResponse, a, b);
  }
}

/**
 * Beji message
 *
 * @generated from message beji.v1.Beji
 */
export class Beji extends Message<Beji> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string player_id = 2;
   */
  playerId = "";

  /**
   * @generated from field: string world_id = 3;
   */
  worldId = "";

  /**
   * @generated from field: string emoji = 4;
   */
  emoji = "";

  /**
   * @generated from field: string name = 5;
   */
  name = "";

  /**
   * @generated from field: common.v1.Position position = 6;
   */
  position?: Position;

  /**
   * @generated from field: common.v1.Position target = 7;
   */
  target?: Position;

  /**
   * @generated from field: bool walk = 8;
   */
  walk = false;

  /**
   * @generated from field: int64 created_at = 9;
   */
  createdAt = protoInt64.zero;

  constructor(data?: PartialMessage<Beji>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.Beji";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "world_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "position", kind: "message", T: Position },
    { no: 7, name: "target", kind: "message", T: Position },
    { no: 8, name: "walk", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "created_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Beji {
    return new Beji().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Beji {
    return new Beji().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Beji {
    return new Beji().fromJsonString(jsonString, options);
  }

  static equals(a: Beji | PlainMessage<Beji> | undefined, b: Beji | PlainMessage<Beji> | undefined): boolean {
    return proto3.util.equals(Beji, a, b);
  }
}

/**
 * BejiPositionUpdate message for real-time sync
 *
 * @generated from message beji.v1.BejiPositionUpdate
 */
export class BejiPositionUpdate extends Message<BejiPositionUpdate> {
  /**
   * @generated from field: string beji_id = 1;
   */
  bejiId = "";

  /**
   * @generated from field: common.v1.Position position = 2;
   */
  position?: Position;

  /**
   * @generated from field: common.v1.Position target = 3;
   */
  target?: Position;

  /**
   * @generated from field: bool walk = 4;
   */
  walk = false;

  constructor(data?: PartialMessage<BejiPositionUpdate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "beji.v1.BejiPositionUpdate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "position", kind: "message", T: Position },
    { no: 3, name: "target", kind: "message", T: Position },
    { no: 4, name: "walk", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BejiPositionUpdate {
    return new BejiPositionUpdate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BejiPositionUpdate {
    return new BejiPositionUpdate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BejiPositionUpdate {
    return new BejiPositionUpdate().fromJsonString(jsonString, options);
  }

  static equals(a: BejiPositionUpdate | PlainMessage<BejiPositionUpdate> | undefined, b: BejiPositionUpdate | PlainMessage<BejiPositionUpdate> | undefined): boolean {
    return proto3.util.equals(BejiPositionUpdate, a, b);
  }
}

