// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts+dts"
// @generated from file beji/v1/beji.proto (package beji.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BejiPositionUpdate, CreateBejiRequest, CreateBejiResponse, GetAllBejiRequest, GetAllBejiResponse, GetBejiForPlayerRequest, GetBejiForPlayerResponse, GetBejiRequest, GetBejiResponse, UpdateBejiRequest, UpdateBejiResponse } from "./beji_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Beji service for managing beji entities
 *
 * @generated from service beji.v1.BejiService
 */
export declare const BejiService: {
  readonly typeName: "beji.v1.BejiService",
  readonly methods: {
    /**
     * GetBeji retrieves a beji by ID
     *
     * @generated from rpc beji.v1.BejiService.GetBeji
     */
    readonly getBeji: {
      readonly name: "GetBeji",
      readonly I: typeof GetBejiRequest,
      readonly O: typeof GetBejiResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetBejiForPlayer retrieves all beji for a specific player
     *
     * @generated from rpc beji.v1.BejiService.GetBejiForPlayer
     */
    readonly getBejiForPlayer: {
      readonly name: "GetBejiForPlayer",
      readonly I: typeof GetBejiForPlayerRequest,
      readonly O: typeof GetBejiForPlayerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetAllBeji retrieves all beji
     *
     * @generated from rpc beji.v1.BejiService.GetAllBeji
     */
    readonly getAllBeji: {
      readonly name: "GetAllBeji",
      readonly I: typeof GetAllBejiRequest,
      readonly O: typeof GetAllBejiResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * CreateBeji creates a new beji
     *
     * @generated from rpc beji.v1.BejiService.CreateBeji
     */
    readonly createBeji: {
      readonly name: "CreateBeji",
      readonly I: typeof CreateBejiRequest,
      readonly O: typeof CreateBejiResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * UpdateBeji updates an existing beji
     *
     * @generated from rpc beji.v1.BejiService.UpdateBeji
     */
    readonly updateBeji: {
      readonly name: "UpdateBeji",
      readonly I: typeof UpdateBejiRequest,
      readonly O: typeof UpdateBejiResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

/**
 * BejiSync service for real-time position and target synchronization
 *
 * @generated from service beji.v1.BejiSyncService
 */
export declare const BejiSyncService: {
  readonly typeName: "beji.v1.BejiSyncService",
  readonly methods: {
    /**
     * SyncBejiPosition streams beji position and target updates
     *
     * @generated from rpc beji.v1.BejiSyncService.SyncBejiPosition
     */
    readonly syncBejiPosition: {
      readonly name: "SyncBejiPosition",
      readonly I: typeof BejiPositionUpdate,
      readonly O: typeof BejiPositionUpdate,
      readonly kind: MethodKind.BiDiStreaming,
    },
  }
};

