// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts+dts"
// @generated from file beji/v1/beji.proto (package beji.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateBejiRequest, CreateBejiResponse, GetAllBejiRequest, GetAllBejiResponse, GetBejiForPlayerRequest, GetBejiForPlayerResponse, GetBejiRequest, GetBejiResponse, UpdateBejiRequest, UpdateBejiResponse } from "./beji_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Beji service for managing beji entities
 *
 * @generated from service beji.v1.BejiService
 */
export const BejiService = {
  typeName: "beji.v1.BejiService",
  methods: {
    /**
     * GetBeji retrieves a beji by ID
     *
     * @generated from rpc beji.v1.BejiService.GetBeji
     */
    getBeji: {
      name: "GetBeji",
      I: GetBejiRequest,
      O: GetBejiResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetBejiForPlayer retrieves all beji for a specific player
     *
     * @generated from rpc beji.v1.BejiService.GetBejiForPlayer
     */
    getBejiForPlayer: {
      name: "GetBejiForPlayer",
      I: GetBejiForPlayerRequest,
      O: GetBejiForPlayerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetAllBeji retrieves all beji
     *
     * @generated from rpc beji.v1.BejiService.GetAllBeji
     */
    getAllBeji: {
      name: "GetAllBeji",
      I: GetAllBejiRequest,
      O: GetAllBejiResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreateBeji creates a new beji
     *
     * @generated from rpc beji.v1.BejiService.CreateBeji
     */
    createBeji: {
      name: "CreateBeji",
      I: CreateBejiRequest,
      O: CreateBejiResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateBeji updates an existing beji
     *
     * @generated from rpc beji.v1.BejiService.UpdateBeji
     */
    updateBeji: {
      name: "UpdateBeji",
      I: UpdateBejiRequest,
      O: UpdateBejiResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

