// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file beji/v1/beji.proto (package beji.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Position } from "../../common/v1/common_pb";

/**
 * Describes the file beji/v1/beji.proto.
 */
export declare const file_beji_v1_beji: GenFile;

/**
 * Request to get a beji by ID
 *
 * @generated from message beji.v1.GetBejiRequest
 */
export declare type GetBejiRequest = Message<"beji.v1.GetBejiRequest"> & {
  /**
   * @generated from field: string beji_id = 1;
   */
  bejiId: string;
};

/**
 * Describes the message beji.v1.GetBejiRequest.
 * Use `create(GetBejiRequestSchema)` to create a new message.
 */
export declare const GetBejiRequestSchema: GenMessage<GetBejiRequest>;

/**
 * Response containing a beji
 *
 * @generated from message beji.v1.GetBejiResponse
 */
export declare type GetBejiResponse = Message<"beji.v1.GetBejiResponse"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.GetBejiResponse.
 * Use `create(GetBejiResponseSchema)` to create a new message.
 */
export declare const GetBejiResponseSchema: GenMessage<GetBejiResponse>;

/**
 * Request to get beji for a player
 *
 * @generated from message beji.v1.GetBejiForPlayerRequest
 */
export declare type GetBejiForPlayerRequest = Message<"beji.v1.GetBejiForPlayerRequest"> & {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;
};

/**
 * Describes the message beji.v1.GetBejiForPlayerRequest.
 * Use `create(GetBejiForPlayerRequestSchema)` to create a new message.
 */
export declare const GetBejiForPlayerRequestSchema: GenMessage<GetBejiForPlayerRequest>;

/**
 * Response containing beji for a player
 *
 * @generated from message beji.v1.GetBejiForPlayerResponse
 */
export declare type GetBejiForPlayerResponse = Message<"beji.v1.GetBejiForPlayerResponse"> & {
  /**
   * @generated from field: repeated beji.v1.Beji beji = 1;
   */
  beji: Beji[];
};

/**
 * Describes the message beji.v1.GetBejiForPlayerResponse.
 * Use `create(GetBejiForPlayerResponseSchema)` to create a new message.
 */
export declare const GetBejiForPlayerResponseSchema: GenMessage<GetBejiForPlayerResponse>;

/**
 * Request to get all beji
 *
 * @generated from message beji.v1.GetAllBejiRequest
 */
export declare type GetAllBejiRequest = Message<"beji.v1.GetAllBejiRequest"> & {
};

/**
 * Describes the message beji.v1.GetAllBejiRequest.
 * Use `create(GetAllBejiRequestSchema)` to create a new message.
 */
export declare const GetAllBejiRequestSchema: GenMessage<GetAllBejiRequest>;

/**
 * Response containing all beji
 *
 * @generated from message beji.v1.GetAllBejiResponse
 */
export declare type GetAllBejiResponse = Message<"beji.v1.GetAllBejiResponse"> & {
  /**
   * @generated from field: repeated beji.v1.Beji beji = 1;
   */
  beji: Beji[];
};

/**
 * Describes the message beji.v1.GetAllBejiResponse.
 * Use `create(GetAllBejiResponseSchema)` to create a new message.
 */
export declare const GetAllBejiResponseSchema: GenMessage<GetAllBejiResponse>;

/**
 * Request to create a beji
 *
 * @generated from message beji.v1.CreateBejiRequest
 */
export declare type CreateBejiRequest = Message<"beji.v1.CreateBejiRequest"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.CreateBejiRequest.
 * Use `create(CreateBejiRequestSchema)` to create a new message.
 */
export declare const CreateBejiRequestSchema: GenMessage<CreateBejiRequest>;

/**
 * Response containing the created beji
 *
 * @generated from message beji.v1.CreateBejiResponse
 */
export declare type CreateBejiResponse = Message<"beji.v1.CreateBejiResponse"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.CreateBejiResponse.
 * Use `create(CreateBejiResponseSchema)` to create a new message.
 */
export declare const CreateBejiResponseSchema: GenMessage<CreateBejiResponse>;

/**
 * Request to update a beji
 *
 * @generated from message beji.v1.UpdateBejiRequest
 */
export declare type UpdateBejiRequest = Message<"beji.v1.UpdateBejiRequest"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.UpdateBejiRequest.
 * Use `create(UpdateBejiRequestSchema)` to create a new message.
 */
export declare const UpdateBejiRequestSchema: GenMessage<UpdateBejiRequest>;

/**
 * Response containing the updated beji
 *
 * @generated from message beji.v1.UpdateBejiResponse
 */
export declare type UpdateBejiResponse = Message<"beji.v1.UpdateBejiResponse"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.UpdateBejiResponse.
 * Use `create(UpdateBejiResponseSchema)` to create a new message.
 */
export declare const UpdateBejiResponseSchema: GenMessage<UpdateBejiResponse>;

/**
 * Beji message
 *
 * @generated from message beji.v1.Beji
 */
export declare type Beji = Message<"beji.v1.Beji"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string player_id = 2;
   */
  playerId: string;

  /**
   * @generated from field: string world_id = 3;
   */
  worldId: string;

  /**
   * @generated from field: string emoji = 4;
   */
  emoji: string;

  /**
   * @generated from field: string name = 5;
   */
  name: string;

  /**
   * @generated from field: common.v1.Position position = 6;
   */
  position?: Position;

  /**
   * @generated from field: common.v1.Position target = 7;
   */
  target?: Position;

  /**
   * @generated from field: bool walk = 8;
   */
  walk: boolean;

  /**
   * @generated from field: int64 created_at = 9;
   */
  createdAt: bigint;
};

/**
 * Describes the message beji.v1.Beji.
 * Use `create(BejiSchema)` to create a new message.
 */
export declare const BejiSchema: GenMessage<Beji>;

/**
 * BejiPositionUpdate message for real-time sync
 *
 * @generated from message beji.v1.BejiPositionUpdate
 */
export declare type BejiPositionUpdate = Message<"beji.v1.BejiPositionUpdate"> & {
  /**
   * @generated from field: string beji_id = 1;
   */
  bejiId: string;

  /**
   * @generated from field: common.v1.Position position = 2;
   */
  position?: Position;

  /**
   * @generated from field: common.v1.Position target = 3;
   */
  target?: Position;

  /**
   * @generated from field: bool walk = 4;
   */
  walk: boolean;
};

/**
 * Describes the message beji.v1.BejiPositionUpdate.
 * Use `create(BejiPositionUpdateSchema)` to create a new message.
 */
export declare const BejiPositionUpdateSchema: GenMessage<BejiPositionUpdate>;

/**
 * Beji service for managing beji entities
 *
 * @generated from service beji.v1.BejiService
 */
export declare const BejiService: GenService<{
  /**
   * GetBeji retrieves a beji by ID
   *
   * @generated from rpc beji.v1.BejiService.GetBeji
   */
  getBeji: {
    methodKind: "unary";
    input: typeof GetBejiRequestSchema;
    output: typeof GetBejiResponseSchema;
  },
  /**
   * GetBejiForPlayer retrieves all beji for a specific player
   *
   * @generated from rpc beji.v1.BejiService.GetBejiForPlayer
   */
  getBejiForPlayer: {
    methodKind: "unary";
    input: typeof GetBejiForPlayerRequestSchema;
    output: typeof GetBejiForPlayerResponseSchema;
  },
  /**
   * GetAllBeji retrieves all beji
   *
   * @generated from rpc beji.v1.BejiService.GetAllBeji
   */
  getAllBeji: {
    methodKind: "unary";
    input: typeof GetAllBejiRequestSchema;
    output: typeof GetAllBejiResponseSchema;
  },
  /**
   * CreateBeji creates a new beji
   *
   * @generated from rpc beji.v1.BejiService.CreateBeji
   */
  createBeji: {
    methodKind: "unary";
    input: typeof CreateBejiRequestSchema;
    output: typeof CreateBejiResponseSchema;
  },
  /**
   * UpdateBeji updates an existing beji
   *
   * @generated from rpc beji.v1.BejiService.UpdateBeji
   */
  updateBeji: {
    methodKind: "unary";
    input: typeof UpdateBejiRequestSchema;
    output: typeof UpdateBejiResponseSchema;
  },
}>;

/**
 * BejiSync service for real-time position and target synchronization
 *
 * @generated from service beji.v1.BejiSyncService
 */
export declare const BejiSyncService: GenService<{
  /**
   * SyncBejiPosition streams beji position and target updates
   *
   * @generated from rpc beji.v1.BejiSyncService.SyncBejiPosition
   */
  syncBejiPosition: {
    methodKind: "bidi_streaming";
    input: typeof BejiPositionUpdateSchema;
    output: typeof BejiPositionUpdateSchema;
  },
}>;

