// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file beji/v1/beji.proto (package beji.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Position } from "../../common/v1/common_pb";
import { file_common_v1_common } from "../../common/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file beji/v1/beji.proto.
 */
export const file_beji_v1_beji: GenFile = /*@__PURE__*/
  fileDesc("ChJiZWppL3YxL2JlamkucHJvdG8SB2JlamkudjEiIQoOR2V0QmVqaVJlcXVlc3QSDwoHYmVqaV9pZBgBIAEoCSIuCg9HZXRCZWppUmVzcG9uc2USGwoEYmVqaRgBIAEoCzINLmJlamkudjEuQmVqaSIsChdHZXRCZWppRm9yUGxheWVyUmVxdWVzdBIRCglwbGF5ZXJfaWQYASABKAkiNwoYR2V0QmVqaUZvclBsYXllclJlc3BvbnNlEhsKBGJlamkYASADKAsyDS5iZWppLnYxLkJlamkiEwoRR2V0QWxsQmVqaVJlcXVlc3QiMQoSR2V0QWxsQmVqaVJlc3BvbnNlEhsKBGJlamkYASADKAsyDS5iZWppLnYxLkJlamkiMAoRQ3JlYXRlQmVqaVJlcXVlc3QSGwoEYmVqaRgBIAEoCzINLmJlamkudjEuQmVqaSIxChJDcmVhdGVCZWppUmVzcG9uc2USGwoEYmVqaRgBIAEoCzINLmJlamkudjEuQmVqaSIwChFVcGRhdGVCZWppUmVxdWVzdBIbCgRiZWppGAEgASgLMg0uYmVqaS52MS5CZWppIjEKElVwZGF0ZUJlamlSZXNwb25zZRIbCgRiZWppGAEgASgLMg0uYmVqaS52MS5CZWppIsIBCgRCZWppEgoKAmlkGAEgASgJEhEKCXBsYXllcl9pZBgCIAEoCRIQCgh3b3JsZF9pZBgDIAEoCRINCgVlbW9qaRgEIAEoCRIMCgRuYW1lGAUgASgJEiUKCHBvc2l0aW9uGAYgASgLMhMuY29tbW9uLnYxLlBvc2l0aW9uEiMKBnRhcmdldBgHIAEoCzITLmNvbW1vbi52MS5Qb3NpdGlvbhIMCgR3YWxrGAggASgIEhIKCmNyZWF0ZWRfYXQYCSABKAMifwoSQmVqaVBvc2l0aW9uVXBkYXRlEg8KB2JlamlfaWQYASABKAkSJQoIcG9zaXRpb24YAiABKAsyEy5jb21tb24udjEuUG9zaXRpb24SIwoGdGFyZ2V0GAMgASgLMhMuY29tbW9uLnYxLlBvc2l0aW9uEgwKBHdhbGsYBCABKAgy+QIKC0JlamlTZXJ2aWNlEjwKB0dldEJlamkSFy5iZWppLnYxLkdldEJlamlSZXF1ZXN0GhguYmVqaS52MS5HZXRCZWppUmVzcG9uc2USVwoQR2V0QmVqaUZvclBsYXllchIgLmJlamkudjEuR2V0QmVqaUZvclBsYXllclJlcXVlc3QaIS5iZWppLnYxLkdldEJlamlGb3JQbGF5ZXJSZXNwb25zZRJFCgpHZXRBbGxCZWppEhouYmVqaS52MS5HZXRBbGxCZWppUmVxdWVzdBobLmJlamkudjEuR2V0QWxsQmVqaVJlc3BvbnNlEkUKCkNyZWF0ZUJlamkSGi5iZWppLnYxLkNyZWF0ZUJlamlSZXF1ZXN0GhsuYmVqaS52MS5DcmVhdGVCZWppUmVzcG9uc2USRQoKVXBkYXRlQmVqaRIaLmJlamkudjEuVXBkYXRlQmVqaVJlcXVlc3QaGy5iZWppLnYxLlVwZGF0ZUJlamlSZXNwb25zZTJjCg9CZWppU3luY1NlcnZpY2USUAoQU3luY0JlamlQb3NpdGlvbhIbLmJlamkudjEuQmVqaVBvc2l0aW9uVXBkYXRlGhsuYmVqaS52MS5CZWppUG9zaXRpb25VcGRhdGUoATABQiNaIWdpdGh1Yi5jb20vcG91eWFqb29uL2JlamkvYmVqaS92MWIGcHJvdG8z", [file_common_v1_common]);

/**
 * Request to get a beji by ID
 *
 * @generated from message beji.v1.GetBejiRequest
 */
export type GetBejiRequest = Message<"beji.v1.GetBejiRequest"> & {
  /**
   * @generated from field: string beji_id = 1;
   */
  bejiId: string;
};

/**
 * Describes the message beji.v1.GetBejiRequest.
 * Use `create(GetBejiRequestSchema)` to create a new message.
 */
export const GetBejiRequestSchema: GenMessage<GetBejiRequest> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 0);

/**
 * Response containing a beji
 *
 * @generated from message beji.v1.GetBejiResponse
 */
export type GetBejiResponse = Message<"beji.v1.GetBejiResponse"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.GetBejiResponse.
 * Use `create(GetBejiResponseSchema)` to create a new message.
 */
export const GetBejiResponseSchema: GenMessage<GetBejiResponse> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 1);

/**
 * Request to get beji for a player
 *
 * @generated from message beji.v1.GetBejiForPlayerRequest
 */
export type GetBejiForPlayerRequest = Message<"beji.v1.GetBejiForPlayerRequest"> & {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;
};

/**
 * Describes the message beji.v1.GetBejiForPlayerRequest.
 * Use `create(GetBejiForPlayerRequestSchema)` to create a new message.
 */
export const GetBejiForPlayerRequestSchema: GenMessage<GetBejiForPlayerRequest> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 2);

/**
 * Response containing beji for a player
 *
 * @generated from message beji.v1.GetBejiForPlayerResponse
 */
export type GetBejiForPlayerResponse = Message<"beji.v1.GetBejiForPlayerResponse"> & {
  /**
   * @generated from field: repeated beji.v1.Beji beji = 1;
   */
  beji: Beji[];
};

/**
 * Describes the message beji.v1.GetBejiForPlayerResponse.
 * Use `create(GetBejiForPlayerResponseSchema)` to create a new message.
 */
export const GetBejiForPlayerResponseSchema: GenMessage<GetBejiForPlayerResponse> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 3);

/**
 * Request to get all beji
 *
 * @generated from message beji.v1.GetAllBejiRequest
 */
export type GetAllBejiRequest = Message<"beji.v1.GetAllBejiRequest"> & {
};

/**
 * Describes the message beji.v1.GetAllBejiRequest.
 * Use `create(GetAllBejiRequestSchema)` to create a new message.
 */
export const GetAllBejiRequestSchema: GenMessage<GetAllBejiRequest> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 4);

/**
 * Response containing all beji
 *
 * @generated from message beji.v1.GetAllBejiResponse
 */
export type GetAllBejiResponse = Message<"beji.v1.GetAllBejiResponse"> & {
  /**
   * @generated from field: repeated beji.v1.Beji beji = 1;
   */
  beji: Beji[];
};

/**
 * Describes the message beji.v1.GetAllBejiResponse.
 * Use `create(GetAllBejiResponseSchema)` to create a new message.
 */
export const GetAllBejiResponseSchema: GenMessage<GetAllBejiResponse> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 5);

/**
 * Request to create a beji
 *
 * @generated from message beji.v1.CreateBejiRequest
 */
export type CreateBejiRequest = Message<"beji.v1.CreateBejiRequest"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.CreateBejiRequest.
 * Use `create(CreateBejiRequestSchema)` to create a new message.
 */
export const CreateBejiRequestSchema: GenMessage<CreateBejiRequest> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 6);

/**
 * Response containing the created beji
 *
 * @generated from message beji.v1.CreateBejiResponse
 */
export type CreateBejiResponse = Message<"beji.v1.CreateBejiResponse"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.CreateBejiResponse.
 * Use `create(CreateBejiResponseSchema)` to create a new message.
 */
export const CreateBejiResponseSchema: GenMessage<CreateBejiResponse> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 7);

/**
 * Request to update a beji
 *
 * @generated from message beji.v1.UpdateBejiRequest
 */
export type UpdateBejiRequest = Message<"beji.v1.UpdateBejiRequest"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.UpdateBejiRequest.
 * Use `create(UpdateBejiRequestSchema)` to create a new message.
 */
export const UpdateBejiRequestSchema: GenMessage<UpdateBejiRequest> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 8);

/**
 * Response containing the updated beji
 *
 * @generated from message beji.v1.UpdateBejiResponse
 */
export type UpdateBejiResponse = Message<"beji.v1.UpdateBejiResponse"> & {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;
};

/**
 * Describes the message beji.v1.UpdateBejiResponse.
 * Use `create(UpdateBejiResponseSchema)` to create a new message.
 */
export const UpdateBejiResponseSchema: GenMessage<UpdateBejiResponse> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 9);

/**
 * Beji message
 *
 * @generated from message beji.v1.Beji
 */
export type Beji = Message<"beji.v1.Beji"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string player_id = 2;
   */
  playerId: string;

  /**
   * @generated from field: string world_id = 3;
   */
  worldId: string;

  /**
   * @generated from field: string emoji = 4;
   */
  emoji: string;

  /**
   * @generated from field: string name = 5;
   */
  name: string;

  /**
   * @generated from field: common.v1.Position position = 6;
   */
  position?: Position;

  /**
   * @generated from field: common.v1.Position target = 7;
   */
  target?: Position;

  /**
   * @generated from field: bool walk = 8;
   */
  walk: boolean;

  /**
   * @generated from field: int64 created_at = 9;
   */
  createdAt: bigint;
};

/**
 * Describes the message beji.v1.Beji.
 * Use `create(BejiSchema)` to create a new message.
 */
export const BejiSchema: GenMessage<Beji> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 10);

/**
 * BejiPositionUpdate message for real-time sync
 *
 * @generated from message beji.v1.BejiPositionUpdate
 */
export type BejiPositionUpdate = Message<"beji.v1.BejiPositionUpdate"> & {
  /**
   * @generated from field: string beji_id = 1;
   */
  bejiId: string;

  /**
   * @generated from field: common.v1.Position position = 2;
   */
  position?: Position;

  /**
   * @generated from field: common.v1.Position target = 3;
   */
  target?: Position;

  /**
   * @generated from field: bool walk = 4;
   */
  walk: boolean;
};

/**
 * Describes the message beji.v1.BejiPositionUpdate.
 * Use `create(BejiPositionUpdateSchema)` to create a new message.
 */
export const BejiPositionUpdateSchema: GenMessage<BejiPositionUpdate> = /*@__PURE__*/
  messageDesc(file_beji_v1_beji, 11);

/**
 * Beji service for managing beji entities
 *
 * @generated from service beji.v1.BejiService
 */
export const BejiService: GenService<{
  /**
   * GetBeji retrieves a beji by ID
   *
   * @generated from rpc beji.v1.BejiService.GetBeji
   */
  getBeji: {
    methodKind: "unary";
    input: typeof GetBejiRequestSchema;
    output: typeof GetBejiResponseSchema;
  },
  /**
   * GetBejiForPlayer retrieves all beji for a specific player
   *
   * @generated from rpc beji.v1.BejiService.GetBejiForPlayer
   */
  getBejiForPlayer: {
    methodKind: "unary";
    input: typeof GetBejiForPlayerRequestSchema;
    output: typeof GetBejiForPlayerResponseSchema;
  },
  /**
   * GetAllBeji retrieves all beji
   *
   * @generated from rpc beji.v1.BejiService.GetAllBeji
   */
  getAllBeji: {
    methodKind: "unary";
    input: typeof GetAllBejiRequestSchema;
    output: typeof GetAllBejiResponseSchema;
  },
  /**
   * CreateBeji creates a new beji
   *
   * @generated from rpc beji.v1.BejiService.CreateBeji
   */
  createBeji: {
    methodKind: "unary";
    input: typeof CreateBejiRequestSchema;
    output: typeof CreateBejiResponseSchema;
  },
  /**
   * UpdateBeji updates an existing beji
   *
   * @generated from rpc beji.v1.BejiService.UpdateBeji
   */
  updateBeji: {
    methodKind: "unary";
    input: typeof UpdateBejiRequestSchema;
    output: typeof UpdateBejiResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_beji_v1_beji, 0);

/**
 * BejiSync service for real-time position and target synchronization
 *
 * @generated from service beji.v1.BejiSyncService
 */
export const BejiSyncService: GenService<{
  /**
   * SyncBejiPosition streams beji position and target updates
   *
   * @generated from rpc beji.v1.BejiSyncService.SyncBejiPosition
   */
  syncBejiPosition: {
    methodKind: "bidi_streaming";
    input: typeof BejiPositionUpdateSchema;
    output: typeof BejiPositionUpdateSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_beji_v1_beji, 1);

