// @generated by protoc-gen-es v1.10.1 with parameter "target=ts+dts"
// @generated from file beji/v1/beji.proto (package beji.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Position } from "../../common/v1/common_pb";

/**
 * Request to get a beji by ID
 *
 * @generated from message beji.v1.GetBejiRequest
 */
export declare class GetBejiRequest extends Message<GetBejiRequest> {
  /**
   * @generated from field: string beji_id = 1;
   */
  bejiId: string;

  constructor(data?: PartialMessage<GetBejiRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.GetBejiRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBejiRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBejiRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBejiRequest;

  static equals(a: GetBejiRequest | PlainMessage<GetBejiRequest> | undefined, b: GetBejiRequest | PlainMessage<GetBejiRequest> | undefined): boolean;
}

/**
 * Response containing a beji
 *
 * @generated from message beji.v1.GetBejiResponse
 */
export declare class GetBejiResponse extends Message<GetBejiResponse> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<GetBejiResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.GetBejiResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBejiResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBejiResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBejiResponse;

  static equals(a: GetBejiResponse | PlainMessage<GetBejiResponse> | undefined, b: GetBejiResponse | PlainMessage<GetBejiResponse> | undefined): boolean;
}

/**
 * Request to get beji for a player
 *
 * @generated from message beji.v1.GetBejiForPlayerRequest
 */
export declare class GetBejiForPlayerRequest extends Message<GetBejiForPlayerRequest> {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;

  constructor(data?: PartialMessage<GetBejiForPlayerRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.GetBejiForPlayerRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBejiForPlayerRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBejiForPlayerRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBejiForPlayerRequest;

  static equals(a: GetBejiForPlayerRequest | PlainMessage<GetBejiForPlayerRequest> | undefined, b: GetBejiForPlayerRequest | PlainMessage<GetBejiForPlayerRequest> | undefined): boolean;
}

/**
 * Response containing beji for a player
 *
 * @generated from message beji.v1.GetBejiForPlayerResponse
 */
export declare class GetBejiForPlayerResponse extends Message<GetBejiForPlayerResponse> {
  /**
   * @generated from field: repeated beji.v1.Beji beji = 1;
   */
  beji: Beji[];

  constructor(data?: PartialMessage<GetBejiForPlayerResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.GetBejiForPlayerResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBejiForPlayerResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBejiForPlayerResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBejiForPlayerResponse;

  static equals(a: GetBejiForPlayerResponse | PlainMessage<GetBejiForPlayerResponse> | undefined, b: GetBejiForPlayerResponse | PlainMessage<GetBejiForPlayerResponse> | undefined): boolean;
}

/**
 * Request to get all beji
 *
 * @generated from message beji.v1.GetAllBejiRequest
 */
export declare class GetAllBejiRequest extends Message<GetAllBejiRequest> {
  constructor(data?: PartialMessage<GetAllBejiRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.GetAllBejiRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllBejiRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllBejiRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllBejiRequest;

  static equals(a: GetAllBejiRequest | PlainMessage<GetAllBejiRequest> | undefined, b: GetAllBejiRequest | PlainMessage<GetAllBejiRequest> | undefined): boolean;
}

/**
 * Response containing all beji
 *
 * @generated from message beji.v1.GetAllBejiResponse
 */
export declare class GetAllBejiResponse extends Message<GetAllBejiResponse> {
  /**
   * @generated from field: repeated beji.v1.Beji beji = 1;
   */
  beji: Beji[];

  constructor(data?: PartialMessage<GetAllBejiResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.GetAllBejiResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllBejiResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllBejiResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllBejiResponse;

  static equals(a: GetAllBejiResponse | PlainMessage<GetAllBejiResponse> | undefined, b: GetAllBejiResponse | PlainMessage<GetAllBejiResponse> | undefined): boolean;
}

/**
 * Request to create a beji
 *
 * @generated from message beji.v1.CreateBejiRequest
 */
export declare class CreateBejiRequest extends Message<CreateBejiRequest> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<CreateBejiRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.CreateBejiRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBejiRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBejiRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBejiRequest;

  static equals(a: CreateBejiRequest | PlainMessage<CreateBejiRequest> | undefined, b: CreateBejiRequest | PlainMessage<CreateBejiRequest> | undefined): boolean;
}

/**
 * Response containing the created beji
 *
 * @generated from message beji.v1.CreateBejiResponse
 */
export declare class CreateBejiResponse extends Message<CreateBejiResponse> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<CreateBejiResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.CreateBejiResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBejiResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBejiResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBejiResponse;

  static equals(a: CreateBejiResponse | PlainMessage<CreateBejiResponse> | undefined, b: CreateBejiResponse | PlainMessage<CreateBejiResponse> | undefined): boolean;
}

/**
 * Request to update a beji
 *
 * @generated from message beji.v1.UpdateBejiRequest
 */
export declare class UpdateBejiRequest extends Message<UpdateBejiRequest> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<UpdateBejiRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.UpdateBejiRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateBejiRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateBejiRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateBejiRequest;

  static equals(a: UpdateBejiRequest | PlainMessage<UpdateBejiRequest> | undefined, b: UpdateBejiRequest | PlainMessage<UpdateBejiRequest> | undefined): boolean;
}

/**
 * Response containing the updated beji
 *
 * @generated from message beji.v1.UpdateBejiResponse
 */
export declare class UpdateBejiResponse extends Message<UpdateBejiResponse> {
  /**
   * @generated from field: beji.v1.Beji beji = 1;
   */
  beji?: Beji;

  constructor(data?: PartialMessage<UpdateBejiResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.UpdateBejiResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateBejiResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateBejiResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateBejiResponse;

  static equals(a: UpdateBejiResponse | PlainMessage<UpdateBejiResponse> | undefined, b: UpdateBejiResponse | PlainMessage<UpdateBejiResponse> | undefined): boolean;
}

/**
 * Beji message
 *
 * @generated from message beji.v1.Beji
 */
export declare class Beji extends Message<Beji> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string player_id = 2;
   */
  playerId: string;

  /**
   * @generated from field: string world_id = 3;
   */
  worldId: string;

  /**
   * @generated from field: string emoji = 4;
   */
  emoji: string;

  /**
   * @generated from field: string name = 5;
   */
  name: string;

  /**
   * @generated from field: common.v1.Position position = 6;
   */
  position?: Position;

  /**
   * @generated from field: common.v1.Position target = 7;
   */
  target?: Position;

  /**
   * @generated from field: bool walk = 8;
   */
  walk: boolean;

  /**
   * @generated from field: int64 created_at = 9;
   */
  createdAt: bigint;

  constructor(data?: PartialMessage<Beji>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.Beji";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Beji;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Beji;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Beji;

  static equals(a: Beji | PlainMessage<Beji> | undefined, b: Beji | PlainMessage<Beji> | undefined): boolean;
}

/**
 * BejiPositionUpdate message for real-time sync
 *
 * @generated from message beji.v1.BejiPositionUpdate
 */
export declare class BejiPositionUpdate extends Message<BejiPositionUpdate> {
  /**
   * @generated from field: string beji_id = 1;
   */
  bejiId: string;

  /**
   * @generated from field: common.v1.Position position = 2;
   */
  position?: Position;

  /**
   * @generated from field: common.v1.Position target = 3;
   */
  target?: Position;

  /**
   * @generated from field: bool walk = 4;
   */
  walk: boolean;

  constructor(data?: PartialMessage<BejiPositionUpdate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beji.v1.BejiPositionUpdate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BejiPositionUpdate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BejiPositionUpdate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BejiPositionUpdate;

  static equals(a: BejiPositionUpdate | PlainMessage<BejiPositionUpdate> | undefined, b: BejiPositionUpdate | PlainMessage<BejiPositionUpdate> | undefined): boolean;
}

