import type { DescService, DescMethod } from '@bufbuild/protobuf';
import type { ConnectRouter, ServiceImpl } from '@connectrpc/connect';

/**
 * Type helper to safely register services generated by protoc-gen-connect-es.
 * 
 * The generated service definitions don't perfectly match DescService at compile time,
 * but they work correctly at runtime because ConnectRouter internally uses createServiceImplSpec
 * which accepts the generated service shape. This helper provides proper type safety
 * by using a more precise type assertion (unknown -> DescService) instead of 'as any'.
 */
export function registerService<
  S extends {
    readonly typeName: string;
    readonly methods: Record<string, {
      readonly name: string;
      readonly I: unknown;
      readonly O: unknown;
      readonly kind: unknown;
    }>;
  }
>(
  router: ConnectRouter,
  service: S,
  implementation: Partial<{
    [K in keyof S['methods']]: S['methods'][K] extends { readonly kind: infer Kind }
      ? Kind extends 'unary'
        ? (request: S['methods'][K]['I'], context?: unknown) => Promise<S['methods'][K]['O']>
        : never
      : never;
  }>
): void {
  // Cast through 'unknown' first (safer than 'as any')
  // The generated services work at runtime because ConnectRouter's internal
  // createServiceImplSpec handles the conversion
  // Partial<> allows registering only some methods, matching ConnectRouter's Partial<ServiceImpl<T>>
  router.service(service as unknown as DescService, implementation as unknown as Partial<ServiceImpl<DescService>>);
}

