// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file staticbeji/v1/staticbeji.proto (package staticbeji.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Position } from "../../common/v1/common_pb";

/**
 * Request to get a static beji by ID
 *
 * @generated from message staticbeji.v1.GetStaticBejiRequest
 */
export class GetStaticBejiRequest extends Message<GetStaticBejiRequest> {
  /**
   * @generated from field: string static_beji_id = 1;
   */
  staticBejiId = "";

  constructor(data?: PartialMessage<GetStaticBejiRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.GetStaticBejiRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "static_beji_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStaticBejiRequest {
    return new GetStaticBejiRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStaticBejiRequest {
    return new GetStaticBejiRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStaticBejiRequest {
    return new GetStaticBejiRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetStaticBejiRequest | PlainMessage<GetStaticBejiRequest> | undefined, b: GetStaticBejiRequest | PlainMessage<GetStaticBejiRequest> | undefined): boolean {
    return proto3.util.equals(GetStaticBejiRequest, a, b);
  }
}

/**
 * Response containing a static beji
 *
 * @generated from message staticbeji.v1.GetStaticBejiResponse
 */
export class GetStaticBejiResponse extends Message<GetStaticBejiResponse> {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;

  constructor(data?: PartialMessage<GetStaticBejiResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.GetStaticBejiResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "static_beji", kind: "message", T: StaticBeji },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStaticBejiResponse {
    return new GetStaticBejiResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStaticBejiResponse {
    return new GetStaticBejiResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStaticBejiResponse {
    return new GetStaticBejiResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetStaticBejiResponse | PlainMessage<GetStaticBejiResponse> | undefined, b: GetStaticBejiResponse | PlainMessage<GetStaticBejiResponse> | undefined): boolean {
    return proto3.util.equals(GetStaticBejiResponse, a, b);
  }
}

/**
 * Request to get static beji for a world
 *
 * @generated from message staticbeji.v1.GetStaticBejiForWorldRequest
 */
export class GetStaticBejiForWorldRequest extends Message<GetStaticBejiForWorldRequest> {
  /**
   * @generated from field: string world_id = 1;
   */
  worldId = "";

  constructor(data?: PartialMessage<GetStaticBejiForWorldRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.GetStaticBejiForWorldRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "world_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStaticBejiForWorldRequest {
    return new GetStaticBejiForWorldRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStaticBejiForWorldRequest {
    return new GetStaticBejiForWorldRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStaticBejiForWorldRequest {
    return new GetStaticBejiForWorldRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetStaticBejiForWorldRequest | PlainMessage<GetStaticBejiForWorldRequest> | undefined, b: GetStaticBejiForWorldRequest | PlainMessage<GetStaticBejiForWorldRequest> | undefined): boolean {
    return proto3.util.equals(GetStaticBejiForWorldRequest, a, b);
  }
}

/**
 * Response containing static beji for a world
 *
 * @generated from message staticbeji.v1.GetStaticBejiForWorldResponse
 */
export class GetStaticBejiForWorldResponse extends Message<GetStaticBejiForWorldResponse> {
  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji: StaticBeji[] = [];

  constructor(data?: PartialMessage<GetStaticBejiForWorldResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.GetStaticBejiForWorldResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "static_beji", kind: "message", T: StaticBeji, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStaticBejiForWorldResponse {
    return new GetStaticBejiForWorldResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStaticBejiForWorldResponse {
    return new GetStaticBejiForWorldResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStaticBejiForWorldResponse {
    return new GetStaticBejiForWorldResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetStaticBejiForWorldResponse | PlainMessage<GetStaticBejiForWorldResponse> | undefined, b: GetStaticBejiForWorldResponse | PlainMessage<GetStaticBejiForWorldResponse> | undefined): boolean {
    return proto3.util.equals(GetStaticBejiForWorldResponse, a, b);
  }
}

/**
 * Request to get all static beji
 *
 * @generated from message staticbeji.v1.GetAllStaticBejiRequest
 */
export class GetAllStaticBejiRequest extends Message<GetAllStaticBejiRequest> {
  constructor(data?: PartialMessage<GetAllStaticBejiRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.GetAllStaticBejiRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllStaticBejiRequest {
    return new GetAllStaticBejiRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllStaticBejiRequest {
    return new GetAllStaticBejiRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllStaticBejiRequest {
    return new GetAllStaticBejiRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAllStaticBejiRequest | PlainMessage<GetAllStaticBejiRequest> | undefined, b: GetAllStaticBejiRequest | PlainMessage<GetAllStaticBejiRequest> | undefined): boolean {
    return proto3.util.equals(GetAllStaticBejiRequest, a, b);
  }
}

/**
 * Response containing all static beji
 *
 * @generated from message staticbeji.v1.GetAllStaticBejiResponse
 */
export class GetAllStaticBejiResponse extends Message<GetAllStaticBejiResponse> {
  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji: StaticBeji[] = [];

  constructor(data?: PartialMessage<GetAllStaticBejiResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.GetAllStaticBejiResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "static_beji", kind: "message", T: StaticBeji, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllStaticBejiResponse {
    return new GetAllStaticBejiResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllStaticBejiResponse {
    return new GetAllStaticBejiResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllStaticBejiResponse {
    return new GetAllStaticBejiResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAllStaticBejiResponse | PlainMessage<GetAllStaticBejiResponse> | undefined, b: GetAllStaticBejiResponse | PlainMessage<GetAllStaticBejiResponse> | undefined): boolean {
    return proto3.util.equals(GetAllStaticBejiResponse, a, b);
  }
}

/**
 * Request to create a static beji
 *
 * @generated from message staticbeji.v1.CreateStaticBejiRequest
 */
export class CreateStaticBejiRequest extends Message<CreateStaticBejiRequest> {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;

  constructor(data?: PartialMessage<CreateStaticBejiRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.CreateStaticBejiRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "static_beji", kind: "message", T: StaticBeji },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateStaticBejiRequest {
    return new CreateStaticBejiRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateStaticBejiRequest {
    return new CreateStaticBejiRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateStaticBejiRequest {
    return new CreateStaticBejiRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateStaticBejiRequest | PlainMessage<CreateStaticBejiRequest> | undefined, b: CreateStaticBejiRequest | PlainMessage<CreateStaticBejiRequest> | undefined): boolean {
    return proto3.util.equals(CreateStaticBejiRequest, a, b);
  }
}

/**
 * Response containing the created static beji
 *
 * @generated from message staticbeji.v1.CreateStaticBejiResponse
 */
export class CreateStaticBejiResponse extends Message<CreateStaticBejiResponse> {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;

  constructor(data?: PartialMessage<CreateStaticBejiResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.CreateStaticBejiResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "static_beji", kind: "message", T: StaticBeji },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateStaticBejiResponse {
    return new CreateStaticBejiResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateStaticBejiResponse {
    return new CreateStaticBejiResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateStaticBejiResponse {
    return new CreateStaticBejiResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateStaticBejiResponse | PlainMessage<CreateStaticBejiResponse> | undefined, b: CreateStaticBejiResponse | PlainMessage<CreateStaticBejiResponse> | undefined): boolean {
    return proto3.util.equals(CreateStaticBejiResponse, a, b);
  }
}

/**
 * StaticBeji message
 *
 * @generated from message staticbeji.v1.StaticBeji
 */
export class StaticBeji extends Message<StaticBeji> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string world_id = 2;
   */
  worldId = "";

  /**
   * @generated from field: int32 emoji_codepoint = 3;
   */
  emojiCodepoint = 0;

  /**
   * @generated from field: string emoji = 4;
   */
  emoji = "";

  /**
   * @generated from field: common.v1.Position position = 5;
   */
  position?: Position;

  /**
   * @generated from field: bool harvested = 6;
   */
  harvested = false;

  constructor(data?: PartialMessage<StaticBeji>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "staticbeji.v1.StaticBeji";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "world_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "emoji_codepoint", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "position", kind: "message", T: Position },
    { no: 6, name: "harvested", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StaticBeji {
    return new StaticBeji().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StaticBeji {
    return new StaticBeji().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StaticBeji {
    return new StaticBeji().fromJsonString(jsonString, options);
  }

  static equals(a: StaticBeji | PlainMessage<StaticBeji> | undefined, b: StaticBeji | PlainMessage<StaticBeji> | undefined): boolean {
    return proto3.util.equals(StaticBeji, a, b);
  }
}

