// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file staticbeji/v1/staticbeji.proto (package staticbeji.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Position } from "../../common/v1/common_pb";

/**
 * Describes the file staticbeji/v1/staticbeji.proto.
 */
export declare const file_staticbeji_v1_staticbeji: GenFile;

/**
 * Request to get a static beji by ID
 *
 * @generated from message staticbeji.v1.GetStaticBejiRequest
 */
export declare type GetStaticBejiRequest = Message<"staticbeji.v1.GetStaticBejiRequest"> & {
  /**
   * @generated from field: string static_beji_id = 1;
   */
  staticBejiId: string;
};

/**
 * Describes the message staticbeji.v1.GetStaticBejiRequest.
 * Use `create(GetStaticBejiRequestSchema)` to create a new message.
 */
export declare const GetStaticBejiRequestSchema: GenMessage<GetStaticBejiRequest>;

/**
 * Response containing a static beji
 *
 * @generated from message staticbeji.v1.GetStaticBejiResponse
 */
export declare type GetStaticBejiResponse = Message<"staticbeji.v1.GetStaticBejiResponse"> & {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;
};

/**
 * Describes the message staticbeji.v1.GetStaticBejiResponse.
 * Use `create(GetStaticBejiResponseSchema)` to create a new message.
 */
export declare const GetStaticBejiResponseSchema: GenMessage<GetStaticBejiResponse>;

/**
 * Request to get static beji for a world
 *
 * @generated from message staticbeji.v1.GetStaticBejiForWorldRequest
 */
export declare type GetStaticBejiForWorldRequest = Message<"staticbeji.v1.GetStaticBejiForWorldRequest"> & {
  /**
   * @generated from field: string world_id = 1;
   */
  worldId: string;
};

/**
 * Describes the message staticbeji.v1.GetStaticBejiForWorldRequest.
 * Use `create(GetStaticBejiForWorldRequestSchema)` to create a new message.
 */
export declare const GetStaticBejiForWorldRequestSchema: GenMessage<GetStaticBejiForWorldRequest>;

/**
 * Response containing static beji for a world
 *
 * @generated from message staticbeji.v1.GetStaticBejiForWorldResponse
 */
export declare type GetStaticBejiForWorldResponse = Message<"staticbeji.v1.GetStaticBejiForWorldResponse"> & {
  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji: StaticBeji[];
};

/**
 * Describes the message staticbeji.v1.GetStaticBejiForWorldResponse.
 * Use `create(GetStaticBejiForWorldResponseSchema)` to create a new message.
 */
export declare const GetStaticBejiForWorldResponseSchema: GenMessage<GetStaticBejiForWorldResponse>;

/**
 * Request to get all static beji
 *
 * @generated from message staticbeji.v1.GetAllStaticBejiRequest
 */
export declare type GetAllStaticBejiRequest = Message<"staticbeji.v1.GetAllStaticBejiRequest"> & {
};

/**
 * Describes the message staticbeji.v1.GetAllStaticBejiRequest.
 * Use `create(GetAllStaticBejiRequestSchema)` to create a new message.
 */
export declare const GetAllStaticBejiRequestSchema: GenMessage<GetAllStaticBejiRequest>;

/**
 * Response containing all static beji
 *
 * @generated from message staticbeji.v1.GetAllStaticBejiResponse
 */
export declare type GetAllStaticBejiResponse = Message<"staticbeji.v1.GetAllStaticBejiResponse"> & {
  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji: StaticBeji[];
};

/**
 * Describes the message staticbeji.v1.GetAllStaticBejiResponse.
 * Use `create(GetAllStaticBejiResponseSchema)` to create a new message.
 */
export declare const GetAllStaticBejiResponseSchema: GenMessage<GetAllStaticBejiResponse>;

/**
 * Request to create a static beji
 *
 * @generated from message staticbeji.v1.CreateStaticBejiRequest
 */
export declare type CreateStaticBejiRequest = Message<"staticbeji.v1.CreateStaticBejiRequest"> & {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;
};

/**
 * Describes the message staticbeji.v1.CreateStaticBejiRequest.
 * Use `create(CreateStaticBejiRequestSchema)` to create a new message.
 */
export declare const CreateStaticBejiRequestSchema: GenMessage<CreateStaticBejiRequest>;

/**
 * Response containing the created static beji
 *
 * @generated from message staticbeji.v1.CreateStaticBejiResponse
 */
export declare type CreateStaticBejiResponse = Message<"staticbeji.v1.CreateStaticBejiResponse"> & {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;
};

/**
 * Describes the message staticbeji.v1.CreateStaticBejiResponse.
 * Use `create(CreateStaticBejiResponseSchema)` to create a new message.
 */
export declare const CreateStaticBejiResponseSchema: GenMessage<CreateStaticBejiResponse>;

/**
 * StaticBeji message
 *
 * @generated from message staticbeji.v1.StaticBeji
 */
export declare type StaticBeji = Message<"staticbeji.v1.StaticBeji"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string world_id = 2;
   */
  worldId: string;

  /**
   * @generated from field: int32 emoji_codepoint = 3;
   */
  emojiCodepoint: number;

  /**
   * @generated from field: string emoji = 4;
   */
  emoji: string;

  /**
   * @generated from field: common.v1.Position position = 5;
   */
  position?: Position;

  /**
   * @generated from field: bool harvested = 6;
   */
  harvested: boolean;
};

/**
 * Describes the message staticbeji.v1.StaticBeji.
 * Use `create(StaticBejiSchema)` to create a new message.
 */
export declare const StaticBejiSchema: GenMessage<StaticBeji>;

/**
 * StaticBeji service for managing static beji entities
 *
 * @generated from service staticbeji.v1.StaticBejiService
 */
export declare const StaticBejiService: GenService<{
  /**
   * GetStaticBeji retrieves a static beji by ID
   *
   * @generated from rpc staticbeji.v1.StaticBejiService.GetStaticBeji
   */
  getStaticBeji: {
    methodKind: "unary";
    input: typeof GetStaticBejiRequestSchema;
    output: typeof GetStaticBejiResponseSchema;
  },
  /**
   * GetStaticBejiForWorld retrieves all static beji for a specific world
   *
   * @generated from rpc staticbeji.v1.StaticBejiService.GetStaticBejiForWorld
   */
  getStaticBejiForWorld: {
    methodKind: "unary";
    input: typeof GetStaticBejiForWorldRequestSchema;
    output: typeof GetStaticBejiForWorldResponseSchema;
  },
  /**
   * GetAllStaticBeji retrieves all static beji
   *
   * @generated from rpc staticbeji.v1.StaticBejiService.GetAllStaticBeji
   */
  getAllStaticBeji: {
    methodKind: "unary";
    input: typeof GetAllStaticBejiRequestSchema;
    output: typeof GetAllStaticBejiResponseSchema;
  },
  /**
   * CreateStaticBeji creates a new static beji
   *
   * @generated from rpc staticbeji.v1.StaticBejiService.CreateStaticBeji
   */
  createStaticBeji: {
    methodKind: "unary";
    input: typeof CreateStaticBejiRequestSchema;
    output: typeof CreateStaticBejiResponseSchema;
  },
}>;

