// @generated by protoc-gen-es v1.10.1 with parameter "target=ts+dts"
// @generated from file staticbeji/v1/staticbeji.proto (package staticbeji.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Position } from "../../common/v1/common_pb";

/**
 * Request to get a static beji by ID
 *
 * @generated from message staticbeji.v1.GetStaticBejiRequest
 */
export declare class GetStaticBejiRequest extends Message<GetStaticBejiRequest> {
  /**
   * @generated from field: string static_beji_id = 1;
   */
  staticBejiId: string;

  constructor(data?: PartialMessage<GetStaticBejiRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.GetStaticBejiRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStaticBejiRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStaticBejiRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStaticBejiRequest;

  static equals(a: GetStaticBejiRequest | PlainMessage<GetStaticBejiRequest> | undefined, b: GetStaticBejiRequest | PlainMessage<GetStaticBejiRequest> | undefined): boolean;
}

/**
 * Response containing a static beji
 *
 * @generated from message staticbeji.v1.GetStaticBejiResponse
 */
export declare class GetStaticBejiResponse extends Message<GetStaticBejiResponse> {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;

  constructor(data?: PartialMessage<GetStaticBejiResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.GetStaticBejiResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStaticBejiResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStaticBejiResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStaticBejiResponse;

  static equals(a: GetStaticBejiResponse | PlainMessage<GetStaticBejiResponse> | undefined, b: GetStaticBejiResponse | PlainMessage<GetStaticBejiResponse> | undefined): boolean;
}

/**
 * Request to get static beji for a world
 *
 * @generated from message staticbeji.v1.GetStaticBejiForWorldRequest
 */
export declare class GetStaticBejiForWorldRequest extends Message<GetStaticBejiForWorldRequest> {
  /**
   * @generated from field: string world_id = 1;
   */
  worldId: string;

  constructor(data?: PartialMessage<GetStaticBejiForWorldRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.GetStaticBejiForWorldRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStaticBejiForWorldRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStaticBejiForWorldRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStaticBejiForWorldRequest;

  static equals(a: GetStaticBejiForWorldRequest | PlainMessage<GetStaticBejiForWorldRequest> | undefined, b: GetStaticBejiForWorldRequest | PlainMessage<GetStaticBejiForWorldRequest> | undefined): boolean;
}

/**
 * Response containing static beji for a world
 *
 * @generated from message staticbeji.v1.GetStaticBejiForWorldResponse
 */
export declare class GetStaticBejiForWorldResponse extends Message<GetStaticBejiForWorldResponse> {
  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji: StaticBeji[];

  constructor(data?: PartialMessage<GetStaticBejiForWorldResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.GetStaticBejiForWorldResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStaticBejiForWorldResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStaticBejiForWorldResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStaticBejiForWorldResponse;

  static equals(a: GetStaticBejiForWorldResponse | PlainMessage<GetStaticBejiForWorldResponse> | undefined, b: GetStaticBejiForWorldResponse | PlainMessage<GetStaticBejiForWorldResponse> | undefined): boolean;
}

/**
 * Request to get all static beji
 *
 * @generated from message staticbeji.v1.GetAllStaticBejiRequest
 */
export declare class GetAllStaticBejiRequest extends Message<GetAllStaticBejiRequest> {
  constructor(data?: PartialMessage<GetAllStaticBejiRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.GetAllStaticBejiRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllStaticBejiRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllStaticBejiRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllStaticBejiRequest;

  static equals(a: GetAllStaticBejiRequest | PlainMessage<GetAllStaticBejiRequest> | undefined, b: GetAllStaticBejiRequest | PlainMessage<GetAllStaticBejiRequest> | undefined): boolean;
}

/**
 * Response containing all static beji
 *
 * @generated from message staticbeji.v1.GetAllStaticBejiResponse
 */
export declare class GetAllStaticBejiResponse extends Message<GetAllStaticBejiResponse> {
  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji: StaticBeji[];

  constructor(data?: PartialMessage<GetAllStaticBejiResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.GetAllStaticBejiResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllStaticBejiResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllStaticBejiResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllStaticBejiResponse;

  static equals(a: GetAllStaticBejiResponse | PlainMessage<GetAllStaticBejiResponse> | undefined, b: GetAllStaticBejiResponse | PlainMessage<GetAllStaticBejiResponse> | undefined): boolean;
}

/**
 * Request to create a static beji
 *
 * @generated from message staticbeji.v1.CreateStaticBejiRequest
 */
export declare class CreateStaticBejiRequest extends Message<CreateStaticBejiRequest> {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;

  constructor(data?: PartialMessage<CreateStaticBejiRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.CreateStaticBejiRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateStaticBejiRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateStaticBejiRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateStaticBejiRequest;

  static equals(a: CreateStaticBejiRequest | PlainMessage<CreateStaticBejiRequest> | undefined, b: CreateStaticBejiRequest | PlainMessage<CreateStaticBejiRequest> | undefined): boolean;
}

/**
 * Response containing the created static beji
 *
 * @generated from message staticbeji.v1.CreateStaticBejiResponse
 */
export declare class CreateStaticBejiResponse extends Message<CreateStaticBejiResponse> {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;

  constructor(data?: PartialMessage<CreateStaticBejiResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.CreateStaticBejiResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateStaticBejiResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateStaticBejiResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateStaticBejiResponse;

  static equals(a: CreateStaticBejiResponse | PlainMessage<CreateStaticBejiResponse> | undefined, b: CreateStaticBejiResponse | PlainMessage<CreateStaticBejiResponse> | undefined): boolean;
}

/**
 * StaticBeji message
 *
 * @generated from message staticbeji.v1.StaticBeji
 */
export declare class StaticBeji extends Message<StaticBeji> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string world_id = 2;
   */
  worldId: string;

  /**
   * @generated from field: int32 emoji_codepoint = 3;
   */
  emojiCodepoint: number;

  /**
   * @generated from field: string emoji = 4;
   */
  emoji: string;

  /**
   * @generated from field: common.v1.Position position = 5;
   */
  position?: Position;

  /**
   * @generated from field: bool harvested = 6;
   */
  harvested: boolean;

  constructor(data?: PartialMessage<StaticBeji>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "staticbeji.v1.StaticBeji";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StaticBeji;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StaticBeji;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StaticBeji;

  static equals(a: StaticBeji | PlainMessage<StaticBeji> | undefined, b: StaticBeji | PlainMessage<StaticBeji> | undefined): boolean;
}

