// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts+dts"
// @generated from file staticbeji/v1/staticbeji.proto (package staticbeji.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateStaticBejiRequest, CreateStaticBejiResponse, GetAllStaticBejiRequest, GetAllStaticBejiResponse, GetStaticBejiForWorldRequest, GetStaticBejiForWorldResponse, GetStaticBejiRequest, GetStaticBejiResponse } from "./staticbeji_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * StaticBeji service for managing static beji entities
 *
 * @generated from service staticbeji.v1.StaticBejiService
 */
export const StaticBejiService = {
  typeName: "staticbeji.v1.StaticBejiService",
  methods: {
    /**
     * GetStaticBeji retrieves a static beji by ID
     *
     * @generated from rpc staticbeji.v1.StaticBejiService.GetStaticBeji
     */
    getStaticBeji: {
      name: "GetStaticBeji",
      I: GetStaticBejiRequest,
      O: GetStaticBejiResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetStaticBejiForWorld retrieves all static beji for a specific world
     *
     * @generated from rpc staticbeji.v1.StaticBejiService.GetStaticBejiForWorld
     */
    getStaticBejiForWorld: {
      name: "GetStaticBejiForWorld",
      I: GetStaticBejiForWorldRequest,
      O: GetStaticBejiForWorldResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetAllStaticBeji retrieves all static beji
     *
     * @generated from rpc staticbeji.v1.StaticBejiService.GetAllStaticBeji
     */
    getAllStaticBeji: {
      name: "GetAllStaticBeji",
      I: GetAllStaticBejiRequest,
      O: GetAllStaticBejiResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreateStaticBeji creates a new static beji
     *
     * @generated from rpc staticbeji.v1.StaticBejiService.CreateStaticBeji
     */
    createStaticBeji: {
      name: "CreateStaticBeji",
      I: CreateStaticBejiRequest,
      O: CreateStaticBejiResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

