// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts+dts"
// @generated from file staticbeji/v1/staticbeji.proto (package staticbeji.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateStaticBejiRequest, CreateStaticBejiResponse, GetAllStaticBejiRequest, GetAllStaticBejiResponse, GetStaticBejiForWorldRequest, GetStaticBejiForWorldResponse, GetStaticBejiRequest, GetStaticBejiResponse } from "./staticbeji_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * StaticBeji service for managing static beji entities
 *
 * @generated from service staticbeji.v1.StaticBejiService
 */
export declare const StaticBejiService: {
  readonly typeName: "staticbeji.v1.StaticBejiService",
  readonly methods: {
    /**
     * GetStaticBeji retrieves a static beji by ID
     *
     * @generated from rpc staticbeji.v1.StaticBejiService.GetStaticBeji
     */
    readonly getStaticBeji: {
      readonly name: "GetStaticBeji",
      readonly I: typeof GetStaticBejiRequest,
      readonly O: typeof GetStaticBejiResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetStaticBejiForWorld retrieves all static beji for a specific world
     *
     * @generated from rpc staticbeji.v1.StaticBejiService.GetStaticBejiForWorld
     */
    readonly getStaticBejiForWorld: {
      readonly name: "GetStaticBejiForWorld",
      readonly I: typeof GetStaticBejiForWorldRequest,
      readonly O: typeof GetStaticBejiForWorldResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetAllStaticBeji retrieves all static beji
     *
     * @generated from rpc staticbeji.v1.StaticBejiService.GetAllStaticBeji
     */
    readonly getAllStaticBeji: {
      readonly name: "GetAllStaticBeji",
      readonly I: typeof GetAllStaticBejiRequest,
      readonly O: typeof GetAllStaticBejiResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * CreateStaticBeji creates a new static beji
     *
     * @generated from rpc staticbeji.v1.StaticBejiService.CreateStaticBeji
     */
    readonly createStaticBeji: {
      readonly name: "CreateStaticBeji",
      readonly I: typeof CreateStaticBejiRequest,
      readonly O: typeof CreateStaticBejiResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

