// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file staticbeji/v1/staticbeji.proto (package staticbeji.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Position } from "../../common/v1/common_pb";
import { file_common_v1_common } from "../../common/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file staticbeji/v1/staticbeji.proto.
 */
export const file_staticbeji_v1_staticbeji: GenFile = /*@__PURE__*/
  fileDesc("Ch5zdGF0aWNiZWppL3YxL3N0YXRpY2JlamkucHJvdG8SDXN0YXRpY2JlamkudjEiLgoUR2V0U3RhdGljQmVqaVJlcXVlc3QSFgoOc3RhdGljX2JlamlfaWQYASABKAkiRwoVR2V0U3RhdGljQmVqaVJlc3BvbnNlEi4KC3N0YXRpY19iZWppGAEgASgLMhkuc3RhdGljYmVqaS52MS5TdGF0aWNCZWppIjAKHEdldFN0YXRpY0JlamlGb3JXb3JsZFJlcXVlc3QSEAoId29ybGRfaWQYASABKAkiTwodR2V0U3RhdGljQmVqaUZvcldvcmxkUmVzcG9uc2USLgoLc3RhdGljX2JlamkYASADKAsyGS5zdGF0aWNiZWppLnYxLlN0YXRpY0JlamkiGQoXR2V0QWxsU3RhdGljQmVqaVJlcXVlc3QiSgoYR2V0QWxsU3RhdGljQmVqaVJlc3BvbnNlEi4KC3N0YXRpY19iZWppGAEgAygLMhkuc3RhdGljYmVqaS52MS5TdGF0aWNCZWppIkkKF0NyZWF0ZVN0YXRpY0JlamlSZXF1ZXN0Ei4KC3N0YXRpY19iZWppGAEgASgLMhkuc3RhdGljYmVqaS52MS5TdGF0aWNCZWppIkoKGENyZWF0ZVN0YXRpY0JlamlSZXNwb25zZRIuCgtzdGF0aWNfYmVqaRgBIAEoCzIZLnN0YXRpY2JlamkudjEuU3RhdGljQmVqaSKMAQoKU3RhdGljQmVqaRIKCgJpZBgBIAEoCRIQCgh3b3JsZF9pZBgCIAEoCRIXCg9lbW9qaV9jb2RlcG9pbnQYAyABKAUSDQoFZW1vamkYBCABKAkSJQoIcG9zaXRpb24YBSABKAsyEy5jb21tb24udjEuUG9zaXRpb24SEQoJaGFydmVzdGVkGAYgASgIMq0DChFTdGF0aWNCZWppU2VydmljZRJaCg1HZXRTdGF0aWNCZWppEiMuc3RhdGljYmVqaS52MS5HZXRTdGF0aWNCZWppUmVxdWVzdBokLnN0YXRpY2JlamkudjEuR2V0U3RhdGljQmVqaVJlc3BvbnNlEnIKFUdldFN0YXRpY0JlamlGb3JXb3JsZBIrLnN0YXRpY2JlamkudjEuR2V0U3RhdGljQmVqaUZvcldvcmxkUmVxdWVzdBosLnN0YXRpY2JlamkudjEuR2V0U3RhdGljQmVqaUZvcldvcmxkUmVzcG9uc2USYwoQR2V0QWxsU3RhdGljQmVqaRImLnN0YXRpY2JlamkudjEuR2V0QWxsU3RhdGljQmVqaVJlcXVlc3QaJy5zdGF0aWNiZWppLnYxLkdldEFsbFN0YXRpY0JlamlSZXNwb25zZRJjChBDcmVhdGVTdGF0aWNCZWppEiYuc3RhdGljYmVqaS52MS5DcmVhdGVTdGF0aWNCZWppUmVxdWVzdBonLnN0YXRpY2JlamkudjEuQ3JlYXRlU3RhdGljQmVqaVJlc3BvbnNlQilaJ2dpdGh1Yi5jb20vcG91eWFqb29uL2Jlamkvc3RhdGljYmVqaS92MWIGcHJvdG8z", [file_common_v1_common]);

/**
 * Request to get a static beji by ID
 *
 * @generated from message staticbeji.v1.GetStaticBejiRequest
 */
export type GetStaticBejiRequest = Message<"staticbeji.v1.GetStaticBejiRequest"> & {
  /**
   * @generated from field: string static_beji_id = 1;
   */
  staticBejiId: string;
};

/**
 * Describes the message staticbeji.v1.GetStaticBejiRequest.
 * Use `create(GetStaticBejiRequestSchema)` to create a new message.
 */
export const GetStaticBejiRequestSchema: GenMessage<GetStaticBejiRequest> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 0);

/**
 * Response containing a static beji
 *
 * @generated from message staticbeji.v1.GetStaticBejiResponse
 */
export type GetStaticBejiResponse = Message<"staticbeji.v1.GetStaticBejiResponse"> & {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;
};

/**
 * Describes the message staticbeji.v1.GetStaticBejiResponse.
 * Use `create(GetStaticBejiResponseSchema)` to create a new message.
 */
export const GetStaticBejiResponseSchema: GenMessage<GetStaticBejiResponse> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 1);

/**
 * Request to get static beji for a world
 *
 * @generated from message staticbeji.v1.GetStaticBejiForWorldRequest
 */
export type GetStaticBejiForWorldRequest = Message<"staticbeji.v1.GetStaticBejiForWorldRequest"> & {
  /**
   * @generated from field: string world_id = 1;
   */
  worldId: string;
};

/**
 * Describes the message staticbeji.v1.GetStaticBejiForWorldRequest.
 * Use `create(GetStaticBejiForWorldRequestSchema)` to create a new message.
 */
export const GetStaticBejiForWorldRequestSchema: GenMessage<GetStaticBejiForWorldRequest> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 2);

/**
 * Response containing static beji for a world
 *
 * @generated from message staticbeji.v1.GetStaticBejiForWorldResponse
 */
export type GetStaticBejiForWorldResponse = Message<"staticbeji.v1.GetStaticBejiForWorldResponse"> & {
  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji: StaticBeji[];
};

/**
 * Describes the message staticbeji.v1.GetStaticBejiForWorldResponse.
 * Use `create(GetStaticBejiForWorldResponseSchema)` to create a new message.
 */
export const GetStaticBejiForWorldResponseSchema: GenMessage<GetStaticBejiForWorldResponse> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 3);

/**
 * Request to get all static beji
 *
 * @generated from message staticbeji.v1.GetAllStaticBejiRequest
 */
export type GetAllStaticBejiRequest = Message<"staticbeji.v1.GetAllStaticBejiRequest"> & {
};

/**
 * Describes the message staticbeji.v1.GetAllStaticBejiRequest.
 * Use `create(GetAllStaticBejiRequestSchema)` to create a new message.
 */
export const GetAllStaticBejiRequestSchema: GenMessage<GetAllStaticBejiRequest> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 4);

/**
 * Response containing all static beji
 *
 * @generated from message staticbeji.v1.GetAllStaticBejiResponse
 */
export type GetAllStaticBejiResponse = Message<"staticbeji.v1.GetAllStaticBejiResponse"> & {
  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji: StaticBeji[];
};

/**
 * Describes the message staticbeji.v1.GetAllStaticBejiResponse.
 * Use `create(GetAllStaticBejiResponseSchema)` to create a new message.
 */
export const GetAllStaticBejiResponseSchema: GenMessage<GetAllStaticBejiResponse> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 5);

/**
 * Request to create a static beji
 *
 * @generated from message staticbeji.v1.CreateStaticBejiRequest
 */
export type CreateStaticBejiRequest = Message<"staticbeji.v1.CreateStaticBejiRequest"> & {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;
};

/**
 * Describes the message staticbeji.v1.CreateStaticBejiRequest.
 * Use `create(CreateStaticBejiRequestSchema)` to create a new message.
 */
export const CreateStaticBejiRequestSchema: GenMessage<CreateStaticBejiRequest> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 6);

/**
 * Response containing the created static beji
 *
 * @generated from message staticbeji.v1.CreateStaticBejiResponse
 */
export type CreateStaticBejiResponse = Message<"staticbeji.v1.CreateStaticBejiResponse"> & {
  /**
   * @generated from field: staticbeji.v1.StaticBeji static_beji = 1;
   */
  staticBeji?: StaticBeji;
};

/**
 * Describes the message staticbeji.v1.CreateStaticBejiResponse.
 * Use `create(CreateStaticBejiResponseSchema)` to create a new message.
 */
export const CreateStaticBejiResponseSchema: GenMessage<CreateStaticBejiResponse> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 7);

/**
 * StaticBeji message
 *
 * @generated from message staticbeji.v1.StaticBeji
 */
export type StaticBeji = Message<"staticbeji.v1.StaticBeji"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string world_id = 2;
   */
  worldId: string;

  /**
   * @generated from field: int32 emoji_codepoint = 3;
   */
  emojiCodepoint: number;

  /**
   * @generated from field: string emoji = 4;
   */
  emoji: string;

  /**
   * @generated from field: common.v1.Position position = 5;
   */
  position?: Position;

  /**
   * @generated from field: bool harvested = 6;
   */
  harvested: boolean;
};

/**
 * Describes the message staticbeji.v1.StaticBeji.
 * Use `create(StaticBejiSchema)` to create a new message.
 */
export const StaticBejiSchema: GenMessage<StaticBeji> = /*@__PURE__*/
  messageDesc(file_staticbeji_v1_staticbeji, 8);

/**
 * StaticBeji service for managing static beji entities
 *
 * @generated from service staticbeji.v1.StaticBejiService
 */
export const StaticBejiService: GenService<{
  /**
   * GetStaticBeji retrieves a static beji by ID
   *
   * @generated from rpc staticbeji.v1.StaticBejiService.GetStaticBeji
   */
  getStaticBeji: {
    methodKind: "unary";
    input: typeof GetStaticBejiRequestSchema;
    output: typeof GetStaticBejiResponseSchema;
  },
  /**
   * GetStaticBejiForWorld retrieves all static beji for a specific world
   *
   * @generated from rpc staticbeji.v1.StaticBejiService.GetStaticBejiForWorld
   */
  getStaticBejiForWorld: {
    methodKind: "unary";
    input: typeof GetStaticBejiForWorldRequestSchema;
    output: typeof GetStaticBejiForWorldResponseSchema;
  },
  /**
   * GetAllStaticBeji retrieves all static beji
   *
   * @generated from rpc staticbeji.v1.StaticBejiService.GetAllStaticBeji
   */
  getAllStaticBeji: {
    methodKind: "unary";
    input: typeof GetAllStaticBejiRequestSchema;
    output: typeof GetAllStaticBejiResponseSchema;
  },
  /**
   * CreateStaticBeji creates a new static beji
   *
   * @generated from rpc staticbeji.v1.StaticBejiService.CreateStaticBeji
   */
  createStaticBeji: {
    methodKind: "unary";
    input: typeof CreateStaticBejiRequestSchema;
    output: typeof CreateStaticBejiResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_staticbeji_v1_staticbeji, 0);

