// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file common/v1/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/common.proto.
 */
export const file_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZjb21tb24vdjEvY29tbW9uLnByb3RvEgljb21tb24udjEiIAoIUG9zaXRpb24SCQoBeBgBIAEoARIJCgF5GAIgASgBQiVaI2dpdGh1Yi5jb20vcG91eWFqb29uL2JlamkvY29tbW9uL3YxYgZwcm90bzM");

/**
 * Position message
 *
 * @generated from message common.v1.Position
 */
export type Position = Message<"common.v1.Position"> & {
  /**
   * @generated from field: double x = 1;
   */
  x: number;

  /**
   * @generated from field: double y = 2;
   */
  y: number;
};

/**
 * Describes the message common.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 0);

