// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file common/v1/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/common.proto.
 */
export declare const file_common_v1_common: GenFile;

/**
 * Position message
 *
 * @generated from message common.v1.Position
 */
export declare type Position = Message<"common.v1.Position"> & {
  /**
   * @generated from field: double x = 1;
   */
  x: number;

  /**
   * @generated from field: double y = 2;
   */
  y: number;
};

/**
 * Describes the message common.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export declare const PositionSchema: GenMessage<Position>;

