// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file world/v1/world.proto (package world.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Player } from "../../player/v1/player_pb";
import type { Beji } from "../../beji/v1/beji_pb";
import type { StaticBeji } from "../../staticbeji/v1/staticbeji_pb";

/**
 * Describes the file world/v1/world.proto.
 */
export declare const file_world_v1_world: GenFile;

/**
 * Request to create a new world
 *
 * @generated from message world.v1.CreateWorldRequest
 */
export declare type CreateWorldRequest = Message<"world.v1.CreateWorldRequest"> & {
  /**
   * Name for the main beji
   *
   * @generated from field: string beji_name = 1;
   */
  bejiName: string;

  /**
   * Emoji codepoints for the main beji
   *
   * @generated from field: repeated int32 emoji_codepoints = 2;
   */
  emojiCodepoints: number[];
};

/**
 * Describes the message world.v1.CreateWorldRequest.
 * Use `create(CreateWorldRequestSchema)` to create a new message.
 */
export declare const CreateWorldRequestSchema: GenMessage<CreateWorldRequest>;

/**
 * Response containing the created world data
 *
 * @generated from message world.v1.CreateWorldResponse
 */
export declare type CreateWorldResponse = Message<"world.v1.CreateWorldResponse"> & {
  /**
   * @generated from field: world.v1.WorldData world = 1;
   */
  world?: WorldData;
};

/**
 * Describes the message world.v1.CreateWorldResponse.
 * Use `create(CreateWorldResponseSchema)` to create a new message.
 */
export declare const CreateWorldResponseSchema: GenMessage<CreateWorldResponse>;

/**
 * Request to get a world
 *
 * @generated from message world.v1.GetWorldRequest
 */
export declare type GetWorldRequest = Message<"world.v1.GetWorldRequest"> & {
  /**
   * @generated from field: string world_id = 1;
   */
  worldId: string;
};

/**
 * Describes the message world.v1.GetWorldRequest.
 * Use `create(GetWorldRequestSchema)` to create a new message.
 */
export declare const GetWorldRequestSchema: GenMessage<GetWorldRequest>;

/**
 * Response containing world data
 *
 * @generated from message world.v1.GetWorldResponse
 */
export declare type GetWorldResponse = Message<"world.v1.GetWorldResponse"> & {
  /**
   * @generated from field: world.v1.WorldData world = 1;
   */
  world?: WorldData;
};

/**
 * Describes the message world.v1.GetWorldResponse.
 * Use `create(GetWorldResponseSchema)` to create a new message.
 */
export declare const GetWorldResponseSchema: GenMessage<GetWorldResponse>;

/**
 * Complete world data structure
 *
 * @generated from message world.v1.WorldData
 */
export declare type WorldData = Message<"world.v1.WorldData"> & {
  /**
   * @generated from field: world.v1.World world = 1;
   */
  world?: World;

  /**
   * @generated from field: player.v1.Player player = 2;
   */
  player?: Player;

  /**
   * @generated from field: beji.v1.Beji beji = 3;
   */
  beji?: Beji;

  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 4;
   */
  staticBeji: StaticBeji[];
};

/**
 * Describes the message world.v1.WorldData.
 * Use `create(WorldDataSchema)` to create a new message.
 */
export declare const WorldDataSchema: GenMessage<WorldData>;

/**
 * World message
 *
 * @generated from message world.v1.World
 */
export declare type World = Message<"world.v1.World"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string main_beji_id = 2;
   */
  mainBejiId: string;

  /**
   * @generated from field: repeated string static_beji_ids = 3;
   */
  staticBejiIds: string[];

  /**
   * @generated from field: int64 created_at = 4;
   */
  createdAt: bigint;
};

/**
 * Describes the message world.v1.World.
 * Use `create(WorldSchema)` to create a new message.
 */
export declare const WorldSchema: GenMessage<World>;

/**
 * World service for creating and retrieving worlds
 *
 * @generated from service world.v1.WorldService
 */
export declare const WorldService: GenService<{
  /**
   * CreateWorld creates a new world for a beji with static bejis
   *
   * @generated from rpc world.v1.WorldService.CreateWorld
   */
  createWorld: {
    methodKind: "unary";
    input: typeof CreateWorldRequestSchema;
    output: typeof CreateWorldResponseSchema;
  },
  /**
   * GetWorld retrieves a world and all its associated data (beji, static bejis)
   *
   * @generated from rpc world.v1.WorldService.GetWorld
   */
  getWorld: {
    methodKind: "unary";
    input: typeof GetWorldRequestSchema;
    output: typeof GetWorldResponseSchema;
  },
}>;

