// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: world/v1/world.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "world.v1";

/** Request to create a new world */
export interface CreateWorldRequest {
  /** Name for the main beji */
  bejiName: string;
  /** Emoji codepoints for the main beji */
  emojiCodepoints: number[];
}

/** Response containing the created world data */
export interface CreateWorldResponse {
  world: WorldData | undefined;
}

/** Request to get a world */
export interface GetWorldRequest {
  worldId: string;
}

/** Response containing world data */
export interface GetWorldResponse {
  world: WorldData | undefined;
}

/** Complete world data structure */
export interface WorldData {
  world: World | undefined;
  player: Player | undefined;
  beji: Beji | undefined;
  staticBeji: StaticBeji[];
}

/** World message */
export interface World {
  id: string;
  mainBejiId: string;
  staticBejiIds: string[];
  createdAt: number;
}

/** Player message */
export interface Player {
  id: string;
  emoji: string;
  emojiCodepoints: number[];
  bejiIds: string[];
  createdAt: number;
}

/** Position message */
export interface Position {
  x: number;
  y: number;
}

/** Beji message */
export interface Beji {
  id: string;
  playerId: string;
  worldId: string;
  emoji: string;
  name: string;
  position: Position | undefined;
  target: Position | undefined;
  walk: boolean;
  createdAt: number;
}

/** StaticBeji message */
export interface StaticBeji {
  id: string;
  worldId: string;
  emojiCodepoint: number;
  emoji: string;
  position: Position | undefined;
  harvested: boolean;
}

function createBaseCreateWorldRequest(): CreateWorldRequest {
  return { bejiName: "", emojiCodepoints: [] };
}

export const CreateWorldRequest = {
  encode(message: CreateWorldRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.bejiName !== "") {
      writer.uint32(10).string(message.bejiName);
    }
    writer.uint32(18).fork();
    for (const v of message.emojiCodepoints) {
      writer.int32(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateWorldRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorldRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.bejiName = reader.string();
          continue;
        case 2:
          if (tag === 16) {
            message.emojiCodepoints.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.emojiCodepoints.push(reader.int32());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateWorldRequest {
    return {
      bejiName: isSet(object.bejiName) ? globalThis.String(object.bejiName) : "",
      emojiCodepoints: globalThis.Array.isArray(object?.emojiCodepoints)
        ? object.emojiCodepoints.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: CreateWorldRequest): unknown {
    const obj: any = {};
    if (message.bejiName !== "") {
      obj.bejiName = message.bejiName;
    }
    if (message.emojiCodepoints?.length) {
      obj.emojiCodepoints = message.emojiCodepoints.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateWorldRequest>, I>>(base?: I): CreateWorldRequest {
    return CreateWorldRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateWorldRequest>, I>>(object: I): CreateWorldRequest {
    const message = createBaseCreateWorldRequest();
    message.bejiName = object.bejiName ?? "";
    message.emojiCodepoints = object.emojiCodepoints?.map((e) => e) || [];
    return message;
  },
};

function createBaseCreateWorldResponse(): CreateWorldResponse {
  return { world: undefined };
}

export const CreateWorldResponse = {
  encode(message: CreateWorldResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.world !== undefined) {
      WorldData.encode(message.world, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateWorldResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorldResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.world = WorldData.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateWorldResponse {
    return { world: isSet(object.world) ? WorldData.fromJSON(object.world) : undefined };
  },

  toJSON(message: CreateWorldResponse): unknown {
    const obj: any = {};
    if (message.world !== undefined) {
      obj.world = WorldData.toJSON(message.world);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateWorldResponse>, I>>(base?: I): CreateWorldResponse {
    return CreateWorldResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateWorldResponse>, I>>(object: I): CreateWorldResponse {
    const message = createBaseCreateWorldResponse();
    message.world = (object.world !== undefined && object.world !== null)
      ? WorldData.fromPartial(object.world)
      : undefined;
    return message;
  },
};

function createBaseGetWorldRequest(): GetWorldRequest {
  return { worldId: "" };
}

export const GetWorldRequest = {
  encode(message: GetWorldRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.worldId !== "") {
      writer.uint32(10).string(message.worldId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetWorldRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorldRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.worldId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWorldRequest {
    return { worldId: isSet(object.worldId) ? globalThis.String(object.worldId) : "" };
  },

  toJSON(message: GetWorldRequest): unknown {
    const obj: any = {};
    if (message.worldId !== "") {
      obj.worldId = message.worldId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWorldRequest>, I>>(base?: I): GetWorldRequest {
    return GetWorldRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWorldRequest>, I>>(object: I): GetWorldRequest {
    const message = createBaseGetWorldRequest();
    message.worldId = object.worldId ?? "";
    return message;
  },
};

function createBaseGetWorldResponse(): GetWorldResponse {
  return { world: undefined };
}

export const GetWorldResponse = {
  encode(message: GetWorldResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.world !== undefined) {
      WorldData.encode(message.world, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetWorldResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorldResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.world = WorldData.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWorldResponse {
    return { world: isSet(object.world) ? WorldData.fromJSON(object.world) : undefined };
  },

  toJSON(message: GetWorldResponse): unknown {
    const obj: any = {};
    if (message.world !== undefined) {
      obj.world = WorldData.toJSON(message.world);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWorldResponse>, I>>(base?: I): GetWorldResponse {
    return GetWorldResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWorldResponse>, I>>(object: I): GetWorldResponse {
    const message = createBaseGetWorldResponse();
    message.world = (object.world !== undefined && object.world !== null)
      ? WorldData.fromPartial(object.world)
      : undefined;
    return message;
  },
};

function createBaseWorldData(): WorldData {
  return { world: undefined, player: undefined, beji: undefined, staticBeji: [] };
}

export const WorldData = {
  encode(message: WorldData, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.world !== undefined) {
      World.encode(message.world, writer.uint32(10).fork()).ldelim();
    }
    if (message.player !== undefined) {
      Player.encode(message.player, writer.uint32(18).fork()).ldelim();
    }
    if (message.beji !== undefined) {
      Beji.encode(message.beji, writer.uint32(26).fork()).ldelim();
    }
    for (const v of message.staticBeji) {
      StaticBeji.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): WorldData {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorldData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.world = World.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.player = Player.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.beji = Beji.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.staticBeji.push(StaticBeji.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorldData {
    return {
      world: isSet(object.world) ? World.fromJSON(object.world) : undefined,
      player: isSet(object.player) ? Player.fromJSON(object.player) : undefined,
      beji: isSet(object.beji) ? Beji.fromJSON(object.beji) : undefined,
      staticBeji: globalThis.Array.isArray(object?.staticBeji)
        ? object.staticBeji.map((e: any) => StaticBeji.fromJSON(e))
        : [],
    };
  },

  toJSON(message: WorldData): unknown {
    const obj: any = {};
    if (message.world !== undefined) {
      obj.world = World.toJSON(message.world);
    }
    if (message.player !== undefined) {
      obj.player = Player.toJSON(message.player);
    }
    if (message.beji !== undefined) {
      obj.beji = Beji.toJSON(message.beji);
    }
    if (message.staticBeji?.length) {
      obj.staticBeji = message.staticBeji.map((e) => StaticBeji.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorldData>, I>>(base?: I): WorldData {
    return WorldData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorldData>, I>>(object: I): WorldData {
    const message = createBaseWorldData();
    message.world = (object.world !== undefined && object.world !== null) ? World.fromPartial(object.world) : undefined;
    message.player = (object.player !== undefined && object.player !== null)
      ? Player.fromPartial(object.player)
      : undefined;
    message.beji = (object.beji !== undefined && object.beji !== null) ? Beji.fromPartial(object.beji) : undefined;
    message.staticBeji = object.staticBeji?.map((e) => StaticBeji.fromPartial(e)) || [];
    return message;
  },
};

function createBaseWorld(): World {
  return { id: "", mainBejiId: "", staticBejiIds: [], createdAt: 0 };
}

export const World = {
  encode(message: World, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.mainBejiId !== "") {
      writer.uint32(18).string(message.mainBejiId);
    }
    for (const v of message.staticBejiIds) {
      writer.uint32(26).string(v!);
    }
    if (message.createdAt !== 0) {
      writer.uint32(32).int64(message.createdAt);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): World {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorld();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.mainBejiId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.staticBejiIds.push(reader.string());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.createdAt = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): World {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      mainBejiId: isSet(object.mainBejiId) ? globalThis.String(object.mainBejiId) : "",
      staticBejiIds: globalThis.Array.isArray(object?.staticBejiIds)
        ? object.staticBejiIds.map((e: any) => globalThis.String(e))
        : [],
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
    };
  },

  toJSON(message: World): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.mainBejiId !== "") {
      obj.mainBejiId = message.mainBejiId;
    }
    if (message.staticBejiIds?.length) {
      obj.staticBejiIds = message.staticBejiIds;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<World>, I>>(base?: I): World {
    return World.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<World>, I>>(object: I): World {
    const message = createBaseWorld();
    message.id = object.id ?? "";
    message.mainBejiId = object.mainBejiId ?? "";
    message.staticBejiIds = object.staticBejiIds?.map((e) => e) || [];
    message.createdAt = object.createdAt ?? 0;
    return message;
  },
};

function createBasePlayer(): Player {
  return { id: "", emoji: "", emojiCodepoints: [], bejiIds: [], createdAt: 0 };
}

export const Player = {
  encode(message: Player, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.emoji !== "") {
      writer.uint32(18).string(message.emoji);
    }
    writer.uint32(26).fork();
    for (const v of message.emojiCodepoints) {
      writer.int32(v);
    }
    writer.ldelim();
    for (const v of message.bejiIds) {
      writer.uint32(34).string(v!);
    }
    if (message.createdAt !== 0) {
      writer.uint32(40).int64(message.createdAt);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Player {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.emoji = reader.string();
          continue;
        case 3:
          if (tag === 24) {
            message.emojiCodepoints.push(reader.int32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.emojiCodepoints.push(reader.int32());
            }

            continue;
          }

          break;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.bejiIds.push(reader.string());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.createdAt = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Player {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      emoji: isSet(object.emoji) ? globalThis.String(object.emoji) : "",
      emojiCodepoints: globalThis.Array.isArray(object?.emojiCodepoints)
        ? object.emojiCodepoints.map((e: any) => globalThis.Number(e))
        : [],
      bejiIds: globalThis.Array.isArray(object?.bejiIds) ? object.bejiIds.map((e: any) => globalThis.String(e)) : [],
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
    };
  },

  toJSON(message: Player): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.emoji !== "") {
      obj.emoji = message.emoji;
    }
    if (message.emojiCodepoints?.length) {
      obj.emojiCodepoints = message.emojiCodepoints.map((e) => Math.round(e));
    }
    if (message.bejiIds?.length) {
      obj.bejiIds = message.bejiIds;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Player>, I>>(base?: I): Player {
    return Player.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Player>, I>>(object: I): Player {
    const message = createBasePlayer();
    message.id = object.id ?? "";
    message.emoji = object.emoji ?? "";
    message.emojiCodepoints = object.emojiCodepoints?.map((e) => e) || [];
    message.bejiIds = object.bejiIds?.map((e) => e) || [];
    message.createdAt = object.createdAt ?? 0;
    return message;
  },
};

function createBasePosition(): Position {
  return { x: 0, y: 0 };
}

export const Position = {
  encode(message: Position, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.x !== 0) {
      writer.uint32(9).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(17).double(message.y);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Position {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePosition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 9) {
            break;
          }

          message.x = reader.double();
          continue;
        case 2:
          if (tag !== 17) {
            break;
          }

          message.y = reader.double();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Position {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: Position): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Position>, I>>(base?: I): Position {
    return Position.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Position>, I>>(object: I): Position {
    const message = createBasePosition();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseBeji(): Beji {
  return {
    id: "",
    playerId: "",
    worldId: "",
    emoji: "",
    name: "",
    position: undefined,
    target: undefined,
    walk: false,
    createdAt: 0,
  };
}

export const Beji = {
  encode(message: Beji, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.playerId !== "") {
      writer.uint32(18).string(message.playerId);
    }
    if (message.worldId !== "") {
      writer.uint32(26).string(message.worldId);
    }
    if (message.emoji !== "") {
      writer.uint32(34).string(message.emoji);
    }
    if (message.name !== "") {
      writer.uint32(42).string(message.name);
    }
    if (message.position !== undefined) {
      Position.encode(message.position, writer.uint32(50).fork()).ldelim();
    }
    if (message.target !== undefined) {
      Position.encode(message.target, writer.uint32(58).fork()).ldelim();
    }
    if (message.walk !== false) {
      writer.uint32(64).bool(message.walk);
    }
    if (message.createdAt !== 0) {
      writer.uint32(72).int64(message.createdAt);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Beji {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBeji();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.playerId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.worldId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.emoji = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.name = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.position = Position.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.target = Position.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.walk = reader.bool();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.createdAt = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Beji {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      playerId: isSet(object.playerId) ? globalThis.String(object.playerId) : "",
      worldId: isSet(object.worldId) ? globalThis.String(object.worldId) : "",
      emoji: isSet(object.emoji) ? globalThis.String(object.emoji) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      position: isSet(object.position) ? Position.fromJSON(object.position) : undefined,
      target: isSet(object.target) ? Position.fromJSON(object.target) : undefined,
      walk: isSet(object.walk) ? globalThis.Boolean(object.walk) : false,
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
    };
  },

  toJSON(message: Beji): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.playerId !== "") {
      obj.playerId = message.playerId;
    }
    if (message.worldId !== "") {
      obj.worldId = message.worldId;
    }
    if (message.emoji !== "") {
      obj.emoji = message.emoji;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.position !== undefined) {
      obj.position = Position.toJSON(message.position);
    }
    if (message.target !== undefined) {
      obj.target = Position.toJSON(message.target);
    }
    if (message.walk !== false) {
      obj.walk = message.walk;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Beji>, I>>(base?: I): Beji {
    return Beji.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Beji>, I>>(object: I): Beji {
    const message = createBaseBeji();
    message.id = object.id ?? "";
    message.playerId = object.playerId ?? "";
    message.worldId = object.worldId ?? "";
    message.emoji = object.emoji ?? "";
    message.name = object.name ?? "";
    message.position = (object.position !== undefined && object.position !== null)
      ? Position.fromPartial(object.position)
      : undefined;
    message.target = (object.target !== undefined && object.target !== null)
      ? Position.fromPartial(object.target)
      : undefined;
    message.walk = object.walk ?? false;
    message.createdAt = object.createdAt ?? 0;
    return message;
  },
};

function createBaseStaticBeji(): StaticBeji {
  return { id: "", worldId: "", emojiCodepoint: 0, emoji: "", position: undefined, harvested: false };
}

export const StaticBeji = {
  encode(message: StaticBeji, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.worldId !== "") {
      writer.uint32(18).string(message.worldId);
    }
    if (message.emojiCodepoint !== 0) {
      writer.uint32(24).int32(message.emojiCodepoint);
    }
    if (message.emoji !== "") {
      writer.uint32(34).string(message.emoji);
    }
    if (message.position !== undefined) {
      Position.encode(message.position, writer.uint32(42).fork()).ldelim();
    }
    if (message.harvested !== false) {
      writer.uint32(48).bool(message.harvested);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StaticBeji {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaticBeji();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.worldId = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.emojiCodepoint = reader.int32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.emoji = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.position = Position.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.harvested = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaticBeji {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      worldId: isSet(object.worldId) ? globalThis.String(object.worldId) : "",
      emojiCodepoint: isSet(object.emojiCodepoint) ? globalThis.Number(object.emojiCodepoint) : 0,
      emoji: isSet(object.emoji) ? globalThis.String(object.emoji) : "",
      position: isSet(object.position) ? Position.fromJSON(object.position) : undefined,
      harvested: isSet(object.harvested) ? globalThis.Boolean(object.harvested) : false,
    };
  },

  toJSON(message: StaticBeji): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.worldId !== "") {
      obj.worldId = message.worldId;
    }
    if (message.emojiCodepoint !== 0) {
      obj.emojiCodepoint = Math.round(message.emojiCodepoint);
    }
    if (message.emoji !== "") {
      obj.emoji = message.emoji;
    }
    if (message.position !== undefined) {
      obj.position = Position.toJSON(message.position);
    }
    if (message.harvested !== false) {
      obj.harvested = message.harvested;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StaticBeji>, I>>(base?: I): StaticBeji {
    return StaticBeji.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StaticBeji>, I>>(object: I): StaticBeji {
    const message = createBaseStaticBeji();
    message.id = object.id ?? "";
    message.worldId = object.worldId ?? "";
    message.emojiCodepoint = object.emojiCodepoint ?? 0;
    message.emoji = object.emoji ?? "";
    message.position = (object.position !== undefined && object.position !== null)
      ? Position.fromPartial(object.position)
      : undefined;
    message.harvested = object.harvested ?? false;
    return message;
  },
};

/** World service for creating and retrieving worlds */
export type WorldServiceDefinition = typeof WorldServiceDefinition;
export const WorldServiceDefinition = {
  name: "WorldService",
  fullName: "world.v1.WorldService",
  methods: {
    /** CreateWorld creates a new world for a beji with static bejis */
    createWorld: {
      name: "CreateWorld",
      requestType: CreateWorldRequest,
      requestStream: false,
      responseType: CreateWorldResponse,
      responseStream: false,
      options: {},
    },
    /** GetWorld retrieves a world and all its associated data (beji, static bejis) */
    getWorld: {
      name: "GetWorld",
      requestType: GetWorldRequest,
      requestStream: false,
      responseType: GetWorldResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
