// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file world/v1/world.proto (package world.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateWorldRequest, CreateWorldResponse, GetWorldRequest, GetWorldResponse } from "./world_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * World service for creating and retrieving worlds
 *
 * @generated from service world.v1.WorldService
 */
export const WorldService = {
  typeName: "world.v1.WorldService",
  methods: {
    /**
     * CreateWorld creates a new world for a beji with static bejis
     *
     * @generated from rpc world.v1.WorldService.CreateWorld
     */
    createWorld: {
      name: "CreateWorld",
      I: CreateWorldRequest,
      O: CreateWorldResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetWorld retrieves a world and all its associated data (beji, static bejis)
     *
     * @generated from rpc world.v1.WorldService.GetWorld
     */
    getWorld: {
      name: "GetWorld",
      I: GetWorldRequest,
      O: GetWorldResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

