// @generated by protoc-gen-es v1.10.1 with parameter "target=ts+dts"
// @generated from file world/v1/world.proto (package world.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Player } from "../../player/v1/player_pb";
import type { Beji } from "../../beji/v1/beji_pb";
import type { StaticBeji } from "../../staticbeji/v1/staticbeji_pb";

/**
 * Request to create a new world
 *
 * @generated from message world.v1.CreateWorldRequest
 */
export declare class CreateWorldRequest extends Message<CreateWorldRequest> {
  /**
   * Name for the main beji
   *
   * @generated from field: string beji_name = 1;
   */
  bejiName: string;

  /**
   * Emoji codepoints for the main beji
   *
   * @generated from field: repeated int32 emoji_codepoints = 2;
   */
  emojiCodepoints: number[];

  constructor(data?: PartialMessage<CreateWorldRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "world.v1.CreateWorldRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateWorldRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateWorldRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateWorldRequest;

  static equals(a: CreateWorldRequest | PlainMessage<CreateWorldRequest> | undefined, b: CreateWorldRequest | PlainMessage<CreateWorldRequest> | undefined): boolean;
}

/**
 * Response containing the created world data
 *
 * @generated from message world.v1.CreateWorldResponse
 */
export declare class CreateWorldResponse extends Message<CreateWorldResponse> {
  /**
   * @generated from field: world.v1.WorldData world = 1;
   */
  world?: WorldData;

  constructor(data?: PartialMessage<CreateWorldResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "world.v1.CreateWorldResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateWorldResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateWorldResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateWorldResponse;

  static equals(a: CreateWorldResponse | PlainMessage<CreateWorldResponse> | undefined, b: CreateWorldResponse | PlainMessage<CreateWorldResponse> | undefined): boolean;
}

/**
 * Request to get a world
 *
 * @generated from message world.v1.GetWorldRequest
 */
export declare class GetWorldRequest extends Message<GetWorldRequest> {
  /**
   * @generated from field: string world_id = 1;
   */
  worldId: string;

  constructor(data?: PartialMessage<GetWorldRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "world.v1.GetWorldRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorldRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorldRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorldRequest;

  static equals(a: GetWorldRequest | PlainMessage<GetWorldRequest> | undefined, b: GetWorldRequest | PlainMessage<GetWorldRequest> | undefined): boolean;
}

/**
 * Response containing world data
 *
 * @generated from message world.v1.GetWorldResponse
 */
export declare class GetWorldResponse extends Message<GetWorldResponse> {
  /**
   * @generated from field: world.v1.WorldData world = 1;
   */
  world?: WorldData;

  constructor(data?: PartialMessage<GetWorldResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "world.v1.GetWorldResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorldResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorldResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorldResponse;

  static equals(a: GetWorldResponse | PlainMessage<GetWorldResponse> | undefined, b: GetWorldResponse | PlainMessage<GetWorldResponse> | undefined): boolean;
}

/**
 * Complete world data structure
 *
 * @generated from message world.v1.WorldData
 */
export declare class WorldData extends Message<WorldData> {
  /**
   * @generated from field: world.v1.World world = 1;
   */
  world?: World;

  /**
   * @generated from field: player.v1.Player player = 2;
   */
  player?: Player;

  /**
   * @generated from field: beji.v1.Beji beji = 3;
   */
  beji?: Beji;

  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 4;
   */
  staticBeji: StaticBeji[];

  constructor(data?: PartialMessage<WorldData>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "world.v1.WorldData";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorldData;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorldData;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorldData;

  static equals(a: WorldData | PlainMessage<WorldData> | undefined, b: WorldData | PlainMessage<WorldData> | undefined): boolean;
}

/**
 * World message
 *
 * @generated from message world.v1.World
 */
export declare class World extends Message<World> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string main_beji_id = 2;
   */
  mainBejiId: string;

  /**
   * @generated from field: repeated string static_beji_ids = 3;
   */
  staticBejiIds: string[];

  /**
   * @generated from field: int64 created_at = 4;
   */
  createdAt: bigint;

  constructor(data?: PartialMessage<World>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "world.v1.World";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): World;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): World;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): World;

  static equals(a: World | PlainMessage<World> | undefined, b: World | PlainMessage<World> | undefined): boolean;
}

