// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file world/v1/world.proto (package world.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Player } from "../../player/v1/player_pb";
import { Beji } from "../../beji/v1/beji_pb";
import { StaticBeji } from "../../staticbeji/v1/staticbeji_pb";

/**
 * Request to create a new world
 *
 * @generated from message world.v1.CreateWorldRequest
 */
export class CreateWorldRequest extends Message<CreateWorldRequest> {
  /**
   * Name for the main beji
   *
   * @generated from field: string beji_name = 1;
   */
  bejiName = "";

  /**
   * Emoji codepoints for the main beji
   *
   * @generated from field: repeated int32 emoji_codepoints = 2;
   */
  emojiCodepoints: number[] = [];

  constructor(data?: PartialMessage<CreateWorldRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.v1.CreateWorldRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "beji_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "emoji_codepoints", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateWorldRequest {
    return new CreateWorldRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateWorldRequest {
    return new CreateWorldRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateWorldRequest {
    return new CreateWorldRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateWorldRequest | PlainMessage<CreateWorldRequest> | undefined, b: CreateWorldRequest | PlainMessage<CreateWorldRequest> | undefined): boolean {
    return proto3.util.equals(CreateWorldRequest, a, b);
  }
}

/**
 * Response containing the created world data
 *
 * @generated from message world.v1.CreateWorldResponse
 */
export class CreateWorldResponse extends Message<CreateWorldResponse> {
  /**
   * @generated from field: world.v1.WorldData world = 1;
   */
  world?: WorldData;

  constructor(data?: PartialMessage<CreateWorldResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.v1.CreateWorldResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "world", kind: "message", T: WorldData },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateWorldResponse {
    return new CreateWorldResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateWorldResponse {
    return new CreateWorldResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateWorldResponse {
    return new CreateWorldResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateWorldResponse | PlainMessage<CreateWorldResponse> | undefined, b: CreateWorldResponse | PlainMessage<CreateWorldResponse> | undefined): boolean {
    return proto3.util.equals(CreateWorldResponse, a, b);
  }
}

/**
 * Request to get a world
 *
 * @generated from message world.v1.GetWorldRequest
 */
export class GetWorldRequest extends Message<GetWorldRequest> {
  /**
   * @generated from field: string world_id = 1;
   */
  worldId = "";

  constructor(data?: PartialMessage<GetWorldRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.v1.GetWorldRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "world_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorldRequest {
    return new GetWorldRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorldRequest {
    return new GetWorldRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorldRequest {
    return new GetWorldRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetWorldRequest | PlainMessage<GetWorldRequest> | undefined, b: GetWorldRequest | PlainMessage<GetWorldRequest> | undefined): boolean {
    return proto3.util.equals(GetWorldRequest, a, b);
  }
}

/**
 * Response containing world data
 *
 * @generated from message world.v1.GetWorldResponse
 */
export class GetWorldResponse extends Message<GetWorldResponse> {
  /**
   * @generated from field: world.v1.WorldData world = 1;
   */
  world?: WorldData;

  constructor(data?: PartialMessage<GetWorldResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.v1.GetWorldResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "world", kind: "message", T: WorldData },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorldResponse {
    return new GetWorldResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorldResponse {
    return new GetWorldResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorldResponse {
    return new GetWorldResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetWorldResponse | PlainMessage<GetWorldResponse> | undefined, b: GetWorldResponse | PlainMessage<GetWorldResponse> | undefined): boolean {
    return proto3.util.equals(GetWorldResponse, a, b);
  }
}

/**
 * Complete world data structure
 *
 * @generated from message world.v1.WorldData
 */
export class WorldData extends Message<WorldData> {
  /**
   * @generated from field: world.v1.World world = 1;
   */
  world?: World;

  /**
   * @generated from field: player.v1.Player player = 2;
   */
  player?: Player;

  /**
   * @generated from field: beji.v1.Beji beji = 3;
   */
  beji?: Beji;

  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 4;
   */
  staticBeji: StaticBeji[] = [];

  constructor(data?: PartialMessage<WorldData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.v1.WorldData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "world", kind: "message", T: World },
    { no: 2, name: "player", kind: "message", T: Player },
    { no: 3, name: "beji", kind: "message", T: Beji },
    { no: 4, name: "static_beji", kind: "message", T: StaticBeji, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorldData {
    return new WorldData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorldData {
    return new WorldData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorldData {
    return new WorldData().fromJsonString(jsonString, options);
  }

  static equals(a: WorldData | PlainMessage<WorldData> | undefined, b: WorldData | PlainMessage<WorldData> | undefined): boolean {
    return proto3.util.equals(WorldData, a, b);
  }
}

/**
 * World message
 *
 * @generated from message world.v1.World
 */
export class World extends Message<World> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string main_beji_id = 2;
   */
  mainBejiId = "";

  /**
   * @generated from field: repeated string static_beji_ids = 3;
   */
  staticBejiIds: string[] = [];

  /**
   * @generated from field: int64 created_at = 4;
   */
  createdAt = protoInt64.zero;

  constructor(data?: PartialMessage<World>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.v1.World";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "main_beji_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "static_beji_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "created_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): World {
    return new World().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): World {
    return new World().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): World {
    return new World().fromJsonString(jsonString, options);
  }

  static equals(a: World | PlainMessage<World> | undefined, b: World | PlainMessage<World> | undefined): boolean {
    return proto3.util.equals(World, a, b);
  }
}

