// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file world/v1/world.proto (package world.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Player } from "../../player/v1/player_pb";
import { file_player_v1_player } from "../../player/v1/player_pb";
import type { Beji } from "../../beji/v1/beji_pb";
import { file_beji_v1_beji } from "../../beji/v1/beji_pb";
import type { StaticBeji } from "../../staticbeji/v1/staticbeji_pb";
import { file_staticbeji_v1_staticbeji } from "../../staticbeji/v1/staticbeji_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file world/v1/world.proto.
 */
export const file_world_v1_world: GenFile = /*@__PURE__*/
  fileDesc("ChR3b3JsZC92MS93b3JsZC5wcm90bxIId29ybGQudjEiQQoSQ3JlYXRlV29ybGRSZXF1ZXN0EhEKCWJlamlfbmFtZRgBIAEoCRIYChBlbW9qaV9jb2RlcG9pbnRzGAIgAygFIjkKE0NyZWF0ZVdvcmxkUmVzcG9uc2USIgoFd29ybGQYASABKAsyEy53b3JsZC52MS5Xb3JsZERhdGEiIwoPR2V0V29ybGRSZXF1ZXN0EhAKCHdvcmxkX2lkGAEgASgJIjYKEEdldFdvcmxkUmVzcG9uc2USIgoFd29ybGQYASABKAsyEy53b3JsZC52MS5Xb3JsZERhdGEimwEKCVdvcmxkRGF0YRIeCgV3b3JsZBgBIAEoCzIPLndvcmxkLnYxLldvcmxkEiEKBnBsYXllchgCIAEoCzIRLnBsYXllci52MS5QbGF5ZXISGwoEYmVqaRgDIAEoCzINLmJlamkudjEuQmVqaRIuCgtzdGF0aWNfYmVqaRgEIAMoCzIZLnN0YXRpY2JlamkudjEuU3RhdGljQmVqaSJWCgVXb3JsZBIKCgJpZBgBIAEoCRIUCgxtYWluX2JlamlfaWQYAiABKAkSFwoPc3RhdGljX2JlamlfaWRzGAMgAygJEhIKCmNyZWF0ZWRfYXQYBCABKAMynQEKDFdvcmxkU2VydmljZRJKCgtDcmVhdGVXb3JsZBIcLndvcmxkLnYxLkNyZWF0ZVdvcmxkUmVxdWVzdBodLndvcmxkLnYxLkNyZWF0ZVdvcmxkUmVzcG9uc2USQQoIR2V0V29ybGQSGS53b3JsZC52MS5HZXRXb3JsZFJlcXVlc3QaGi53b3JsZC52MS5HZXRXb3JsZFJlc3BvbnNlQiRaImdpdGh1Yi5jb20vcG91eWFqb29uL2Jlamkvd29ybGQvdjFiBnByb3RvMw", [file_player_v1_player, file_beji_v1_beji, file_staticbeji_v1_staticbeji]);

/**
 * Request to create a new world
 *
 * @generated from message world.v1.CreateWorldRequest
 */
export type CreateWorldRequest = Message<"world.v1.CreateWorldRequest"> & {
  /**
   * Name for the main beji
   *
   * @generated from field: string beji_name = 1;
   */
  bejiName: string;

  /**
   * Emoji codepoints for the main beji
   *
   * @generated from field: repeated int32 emoji_codepoints = 2;
   */
  emojiCodepoints: number[];
};

/**
 * Describes the message world.v1.CreateWorldRequest.
 * Use `create(CreateWorldRequestSchema)` to create a new message.
 */
export const CreateWorldRequestSchema: GenMessage<CreateWorldRequest> = /*@__PURE__*/
  messageDesc(file_world_v1_world, 0);

/**
 * Response containing the created world data
 *
 * @generated from message world.v1.CreateWorldResponse
 */
export type CreateWorldResponse = Message<"world.v1.CreateWorldResponse"> & {
  /**
   * @generated from field: world.v1.WorldData world = 1;
   */
  world?: WorldData;
};

/**
 * Describes the message world.v1.CreateWorldResponse.
 * Use `create(CreateWorldResponseSchema)` to create a new message.
 */
export const CreateWorldResponseSchema: GenMessage<CreateWorldResponse> = /*@__PURE__*/
  messageDesc(file_world_v1_world, 1);

/**
 * Request to get a world
 *
 * @generated from message world.v1.GetWorldRequest
 */
export type GetWorldRequest = Message<"world.v1.GetWorldRequest"> & {
  /**
   * @generated from field: string world_id = 1;
   */
  worldId: string;
};

/**
 * Describes the message world.v1.GetWorldRequest.
 * Use `create(GetWorldRequestSchema)` to create a new message.
 */
export const GetWorldRequestSchema: GenMessage<GetWorldRequest> = /*@__PURE__*/
  messageDesc(file_world_v1_world, 2);

/**
 * Response containing world data
 *
 * @generated from message world.v1.GetWorldResponse
 */
export type GetWorldResponse = Message<"world.v1.GetWorldResponse"> & {
  /**
   * @generated from field: world.v1.WorldData world = 1;
   */
  world?: WorldData;
};

/**
 * Describes the message world.v1.GetWorldResponse.
 * Use `create(GetWorldResponseSchema)` to create a new message.
 */
export const GetWorldResponseSchema: GenMessage<GetWorldResponse> = /*@__PURE__*/
  messageDesc(file_world_v1_world, 3);

/**
 * Complete world data structure
 *
 * @generated from message world.v1.WorldData
 */
export type WorldData = Message<"world.v1.WorldData"> & {
  /**
   * @generated from field: world.v1.World world = 1;
   */
  world?: World;

  /**
   * @generated from field: player.v1.Player player = 2;
   */
  player?: Player;

  /**
   * @generated from field: beji.v1.Beji beji = 3;
   */
  beji?: Beji;

  /**
   * @generated from field: repeated staticbeji.v1.StaticBeji static_beji = 4;
   */
  staticBeji: StaticBeji[];
};

/**
 * Describes the message world.v1.WorldData.
 * Use `create(WorldDataSchema)` to create a new message.
 */
export const WorldDataSchema: GenMessage<WorldData> = /*@__PURE__*/
  messageDesc(file_world_v1_world, 4);

/**
 * World message
 *
 * @generated from message world.v1.World
 */
export type World = Message<"world.v1.World"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string main_beji_id = 2;
   */
  mainBejiId: string;

  /**
   * @generated from field: repeated string static_beji_ids = 3;
   */
  staticBejiIds: string[];

  /**
   * @generated from field: int64 created_at = 4;
   */
  createdAt: bigint;
};

/**
 * Describes the message world.v1.World.
 * Use `create(WorldSchema)` to create a new message.
 */
export const WorldSchema: GenMessage<World> = /*@__PURE__*/
  messageDesc(file_world_v1_world, 5);

/**
 * World service for creating and retrieving worlds
 *
 * @generated from service world.v1.WorldService
 */
export const WorldService: GenService<{
  /**
   * CreateWorld creates a new world for a beji with static bejis
   *
   * @generated from rpc world.v1.WorldService.CreateWorld
   */
  createWorld: {
    methodKind: "unary";
    input: typeof CreateWorldRequestSchema;
    output: typeof CreateWorldResponseSchema;
  },
  /**
   * GetWorld retrieves a world and all its associated data (beji, static bejis)
   *
   * @generated from rpc world.v1.WorldService.GetWorld
   */
  getWorld: {
    methodKind: "unary";
    input: typeof GetWorldRequestSchema;
    output: typeof GetWorldResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_world_v1_world, 0);

