// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file echo/v1/echo.proto (package echo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file echo/v1/echo.proto.
 */
export const file_echo_v1_echo: GenFile = /*@__PURE__*/
  fileDesc("ChJlY2hvL3YxL2VjaG8ucHJvdG8SB2VjaG8udjEiGwoLRWNob1JlcXVlc3QSDAoEdGV4dBgBIAEoCSIcCgxFY2hvUmVzcG9uc2USDAoEdGV4dBgBIAEoCTJCCgtFY2hvU2VydmljZRIzCgRFY2hvEhQuZWNoby52MS5FY2hvUmVxdWVzdBoVLmVjaG8udjEuRWNob1Jlc3BvbnNlQiNaIWdpdGh1Yi5jb20vcG91eWFqb29uL2JlamkvZWNoby92MWIGcHJvdG8z");

/**
 * @generated from message echo.v1.EchoRequest
 */
export type EchoRequest = Message<"echo.v1.EchoRequest"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message echo.v1.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export const EchoRequestSchema: GenMessage<EchoRequest> = /*@__PURE__*/
  messageDesc(file_echo_v1_echo, 0);

/**
 * @generated from message echo.v1.EchoResponse
 */
export type EchoResponse = Message<"echo.v1.EchoResponse"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message echo.v1.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export const EchoResponseSchema: GenMessage<EchoResponse> = /*@__PURE__*/
  messageDesc(file_echo_v1_echo, 1);

/**
 * Simple example service; define RPCs here instead of REST.
 *
 * @generated from service echo.v1.EchoService
 */
export const EchoService: GenService<{
  /**
   * @generated from rpc echo.v1.EchoService.Echo
   */
  echo: {
    methodKind: "unary";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_echo_v1_echo, 0);

