// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file echo/v1/echo.proto (package echo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file echo/v1/echo.proto.
 */
export declare const file_echo_v1_echo: GenFile;

/**
 * @generated from message echo.v1.EchoRequest
 */
export declare type EchoRequest = Message<"echo.v1.EchoRequest"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message echo.v1.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export declare const EchoRequestSchema: GenMessage<EchoRequest>;

/**
 * @generated from message echo.v1.EchoResponse
 */
export declare type EchoResponse = Message<"echo.v1.EchoResponse"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message echo.v1.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export declare const EchoResponseSchema: GenMessage<EchoResponse>;

/**
 * Simple example service; define RPCs here instead of REST.
 *
 * @generated from service echo.v1.EchoService
 */
export declare const EchoService: GenService<{
  /**
   * @generated from rpc echo.v1.EchoService.Echo
   */
  echo: {
    methodKind: "unary";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
}>;

