// @generated by protoc-gen-es v1.10.1 with parameter "target=ts+dts"
// @generated from file echo/v1/echo.proto (package echo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message echo.v1.EchoRequest
 */
export declare class EchoRequest extends Message<EchoRequest> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<EchoRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "echo.v1.EchoRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EchoRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EchoRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EchoRequest;

  static equals(a: EchoRequest | PlainMessage<EchoRequest> | undefined, b: EchoRequest | PlainMessage<EchoRequest> | undefined): boolean;
}

/**
 * @generated from message echo.v1.EchoResponse
 */
export declare class EchoResponse extends Message<EchoResponse> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<EchoResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "echo.v1.EchoResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EchoResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EchoResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EchoResponse;

  static equals(a: EchoResponse | PlainMessage<EchoResponse> | undefined, b: EchoResponse | PlainMessage<EchoResponse> | undefined): boolean;
}

