// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts+dts"
// @generated from file echo/v1/echo.proto (package echo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EchoRequest, EchoResponse } from "./echo_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Simple example service; define RPCs here instead of REST.
 *
 * @generated from service echo.v1.EchoService
 */
export declare const EchoService: {
  readonly typeName: "echo.v1.EchoService",
  readonly methods: {
    /**
     * @generated from rpc echo.v1.EchoService.Echo
     */
    readonly echo: {
      readonly name: "Echo",
      readonly I: typeof EchoRequest,
      readonly O: typeof EchoResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

