// @generated by protoc-gen-es v1.10.1 with parameter "target=ts+dts"
// @generated from file config/v1/config.proto (package config.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Request to get public configuration
 *
 * @generated from message config.v1.GetPublicConfigRequest
 */
export declare class GetPublicConfigRequest extends Message<GetPublicConfigRequest> {
  constructor(data?: PartialMessage<GetPublicConfigRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "config.v1.GetPublicConfigRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPublicConfigRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPublicConfigRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPublicConfigRequest;

  static equals(a: GetPublicConfigRequest | PlainMessage<GetPublicConfigRequest> | undefined, b: GetPublicConfigRequest | PlainMessage<GetPublicConfigRequest> | undefined): boolean;
}

/**
 * Response containing public configuration
 *
 * @generated from message config.v1.GetPublicConfigResponse
 */
export declare class GetPublicConfigResponse extends Message<GetPublicConfigResponse> {
  /**
   * Google OAuth client ID for authentication
   *
   * @generated from field: string google_client_id = 1;
   */
  googleClientId: string;

  constructor(data?: PartialMessage<GetPublicConfigResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "config.v1.GetPublicConfigResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPublicConfigResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPublicConfigResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPublicConfigResponse;

  static equals(a: GetPublicConfigResponse | PlainMessage<GetPublicConfigResponse> | undefined, b: GetPublicConfigResponse | PlainMessage<GetPublicConfigResponse> | undefined): boolean;
}

