// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file config/v1/config.proto (package config.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file config/v1/config.proto.
 */
export declare const file_config_v1_config: GenFile;

/**
 * Request to get public configuration
 *
 * @generated from message config.v1.GetPublicConfigRequest
 */
export declare type GetPublicConfigRequest = Message<"config.v1.GetPublicConfigRequest"> & {
};

/**
 * Describes the message config.v1.GetPublicConfigRequest.
 * Use `create(GetPublicConfigRequestSchema)` to create a new message.
 */
export declare const GetPublicConfigRequestSchema: GenMessage<GetPublicConfigRequest>;

/**
 * Response containing public configuration
 *
 * @generated from message config.v1.GetPublicConfigResponse
 */
export declare type GetPublicConfigResponse = Message<"config.v1.GetPublicConfigResponse"> & {
  /**
   * Google OAuth client ID for authentication
   *
   * @generated from field: string google_client_id = 1;
   */
  googleClientId: string;
};

/**
 * Describes the message config.v1.GetPublicConfigResponse.
 * Use `create(GetPublicConfigResponseSchema)` to create a new message.
 */
export declare const GetPublicConfigResponseSchema: GenMessage<GetPublicConfigResponse>;

/**
 * Configuration service for public client configuration
 *
 * @generated from service config.v1.ConfigService
 */
export declare const ConfigService: GenService<{
  /**
   * GetPublicConfig retrieves public configuration that does not require authentication
   *
   * @generated from rpc config.v1.ConfigService.GetPublicConfig
   */
  getPublicConfig: {
    methodKind: "unary";
    input: typeof GetPublicConfigRequestSchema;
    output: typeof GetPublicConfigResponseSchema;
  },
}>;

