// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts+dts"
// @generated from file config/v1/config.proto (package config.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetPublicConfigRequest, GetPublicConfigResponse } from "./config_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Configuration service for public client configuration
 *
 * @generated from service config.v1.ConfigService
 */
export declare const ConfigService: {
  readonly typeName: "config.v1.ConfigService",
  readonly methods: {
    /**
     * GetPublicConfig retrieves public configuration that does not require authentication
     *
     * @generated from rpc config.v1.ConfigService.GetPublicConfig
     */
    readonly getPublicConfig: {
      readonly name: "GetPublicConfig",
      readonly I: typeof GetPublicConfigRequest,
      readonly O: typeof GetPublicConfigResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

