// @generated by protoc-gen-es v2.10.0 with parameter "target=ts+dts"
// @generated from file config/v1/config.proto (package config.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file config/v1/config.proto.
 */
export const file_config_v1_config: GenFile = /*@__PURE__*/
  fileDesc("ChZjb25maWcvdjEvY29uZmlnLnByb3RvEgljb25maWcudjEiGAoWR2V0UHVibGljQ29uZmlnUmVxdWVzdCIzChdHZXRQdWJsaWNDb25maWdSZXNwb25zZRIYChBnb29nbGVfY2xpZW50X2lkGAEgASgJMmkKDUNvbmZpZ1NlcnZpY2USWAoPR2V0UHVibGljQ29uZmlnEiEuY29uZmlnLnYxLkdldFB1YmxpY0NvbmZpZ1JlcXVlc3QaIi5jb25maWcudjEuR2V0UHVibGljQ29uZmlnUmVzcG9uc2VCJVojZ2l0aHViLmNvbS9wb3V5YWpvb24vYmVqaS9jb25maWcvdjFiBnByb3RvMw");

/**
 * Request to get public configuration
 *
 * @generated from message config.v1.GetPublicConfigRequest
 */
export type GetPublicConfigRequest = Message<"config.v1.GetPublicConfigRequest"> & {
};

/**
 * Describes the message config.v1.GetPublicConfigRequest.
 * Use `create(GetPublicConfigRequestSchema)` to create a new message.
 */
export const GetPublicConfigRequestSchema: GenMessage<GetPublicConfigRequest> = /*@__PURE__*/
  messageDesc(file_config_v1_config, 0);

/**
 * Response containing public configuration
 *
 * @generated from message config.v1.GetPublicConfigResponse
 */
export type GetPublicConfigResponse = Message<"config.v1.GetPublicConfigResponse"> & {
  /**
   * Google OAuth client ID for authentication
   *
   * @generated from field: string google_client_id = 1;
   */
  googleClientId: string;
};

/**
 * Describes the message config.v1.GetPublicConfigResponse.
 * Use `create(GetPublicConfigResponseSchema)` to create a new message.
 */
export const GetPublicConfigResponseSchema: GenMessage<GetPublicConfigResponse> = /*@__PURE__*/
  messageDesc(file_config_v1_config, 1);

/**
 * Configuration service for public client configuration
 *
 * @generated from service config.v1.ConfigService
 */
export const ConfigService: GenService<{
  /**
   * GetPublicConfig retrieves public configuration that does not require authentication
   *
   * @generated from rpc config.v1.ConfigService.GetPublicConfig
   */
  getPublicConfig: {
    methodKind: "unary";
    input: typeof GetPublicConfigRequestSchema;
    output: typeof GetPublicConfigResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_config_v1_config, 0);

