// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file config/v1/config.proto (package config.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Request to get public configuration
 *
 * @generated from message config.v1.GetPublicConfigRequest
 */
export class GetPublicConfigRequest extends Message<GetPublicConfigRequest> {
  constructor(data?: PartialMessage<GetPublicConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "config.v1.GetPublicConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPublicConfigRequest {
    return new GetPublicConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPublicConfigRequest {
    return new GetPublicConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPublicConfigRequest {
    return new GetPublicConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPublicConfigRequest | PlainMessage<GetPublicConfigRequest> | undefined, b: GetPublicConfigRequest | PlainMessage<GetPublicConfigRequest> | undefined): boolean {
    return proto3.util.equals(GetPublicConfigRequest, a, b);
  }
}

/**
 * Response containing public configuration
 *
 * @generated from message config.v1.GetPublicConfigResponse
 */
export class GetPublicConfigResponse extends Message<GetPublicConfigResponse> {
  /**
   * Google OAuth client ID for authentication
   *
   * @generated from field: string google_client_id = 1;
   */
  googleClientId = "";

  constructor(data?: PartialMessage<GetPublicConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "config.v1.GetPublicConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "google_client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPublicConfigResponse {
    return new GetPublicConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPublicConfigResponse {
    return new GetPublicConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPublicConfigResponse {
    return new GetPublicConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetPublicConfigResponse | PlainMessage<GetPublicConfigResponse> | undefined, b: GetPublicConfigResponse | PlainMessage<GetPublicConfigResponse> | undefined): boolean {
    return proto3.util.equals(GetPublicConfigResponse, a, b);
  }
}

